(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "e1b8c1a1-ae7e-4521-bdbd-4ced1b715801" of type Constants$Constant
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var recipesApiBaseUrl1 = constants.Constant.createIn(unit);
	recipesApiBaseUrl1.name = "RecipesApiBaseUrl";
	recipesApiBaseUrl1.type = stringType1;   // Note: for this property a default value is defined.
	recipesApiBaseUrl1.defaultValue = "http://localhost:8080/mendix-recipes";

})