(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "4359028c-9773-4ce0-bcd3-aae00ba4cc04" of type Constants$Constant
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var recipesApiBaseUrl1 = constants.Constant.createIn(unit);
	recipesApiBaseUrl1.name = "RecipesApiBaseUrl";
	recipesApiBaseUrl1.type = stringType1;   // Note: for this property a default value is defined.
	recipesApiBaseUrl1.defaultValue = "http://localhost:8080/mendix-recipes";

})