(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "07d42dc6-5372-4b1e-987c-435a4ee1657a" of type ExportMappings$ExportMapping
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var exportValueMappingElement1 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement1.elementType = mappings.ElementType.Value;
	exportValueMappingElement1.jsonPath = "(Object)|name";
	exportValueMappingElement1.maxOccurs = 1;
	exportValueMappingElement1.nillable = true;
	exportValueMappingElement1.exposedName = "Name";
	exportValueMappingElement1.type = stringType1;   // Note: for this property a default value is defined.
	exportValueMappingElement1.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement1.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Name");
	exportValueMappingElement1.maxLength = 0;

	var stringType2 = datatypes.StringType.create(model);

	var exportValueMappingElement2 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement2.elementType = mappings.ElementType.Value;
	exportValueMappingElement2.jsonPath = "(Object)|description";
	exportValueMappingElement2.maxOccurs = 1;
	exportValueMappingElement2.nillable = true;
	exportValueMappingElement2.exposedName = "Description";
	exportValueMappingElement2.type = stringType2;   // Note: for this property a default value is defined.
	exportValueMappingElement2.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement2.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Description");
	exportValueMappingElement2.maxLength = 0;

	var stringType3 = datatypes.StringType.create(model);

	var exportValueMappingElement3 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement3.elementType = mappings.ElementType.Value;
	exportValueMappingElement3.jsonPath = "(Object)|author";
	exportValueMappingElement3.maxOccurs = 1;
	exportValueMappingElement3.nillable = true;
	exportValueMappingElement3.exposedName = "Author";
	exportValueMappingElement3.type = stringType3;   // Note: for this property a default value is defined.
	exportValueMappingElement3.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement3.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Author");
	exportValueMappingElement3.maxLength = 0;

	var dateTimeType1 = datatypes.DateTimeType.create(model);

	var exportValueMappingElement4 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement4.elementType = mappings.ElementType.Value;
	exportValueMappingElement4.jsonPath = "(Object)|postedAt";
	exportValueMappingElement4.maxOccurs = 1;
	exportValueMappingElement4.nillable = true;
	exportValueMappingElement4.exposedName = "PostedAt";
	exportValueMappingElement4.type = dateTimeType1;   // Note: for this property a default value is defined.
	exportValueMappingElement4.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.DateTime;
	exportValueMappingElement4.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedAt");

	var stringType4 = datatypes.StringType.create(model);

	var exportValueMappingElement5 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement5.elementType = mappings.ElementType.Value;
	exportValueMappingElement5.jsonPath = "(Object)|postedTo";
	exportValueMappingElement5.maxOccurs = 1;
	exportValueMappingElement5.nillable = true;
	exportValueMappingElement5.exposedName = "PostedTo";
	exportValueMappingElement5.type = stringType4;   // Note: for this property a default value is defined.
	exportValueMappingElement5.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement5.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedTo");
	exportValueMappingElement5.maxLength = 0;

	var integerType1 = datatypes.IntegerType.create(model);

	var exportValueMappingElement6 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement6.elementType = mappings.ElementType.Value;
	exportValueMappingElement6.jsonPath = "(Object)|preparationTimeInMinutes";
	exportValueMappingElement6.maxOccurs = 1;
	exportValueMappingElement6.nillable = true;
	exportValueMappingElement6.exposedName = "PreparationTimeInMinutes";
	exportValueMappingElement6.type = integerType1;   // Note: for this property a default value is defined.
	exportValueMappingElement6.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.Integer;
	exportValueMappingElement6.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PreparationTimeInMinutes");

	var stringType5 = datatypes.StringType.create(model);

	var exportValueMappingElement7 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement7.elementType = mappings.ElementType.Value;
	exportValueMappingElement7.jsonPath = "(Object)|steps|(Wrapper)|(Value)";
	exportValueMappingElement7.maxOccurs = 1;
	exportValueMappingElement7.nillable = true;
	exportValueMappingElement7.exposedName = "Value";
	exportValueMappingElement7.type = stringType5;   // Note: for this property a default value is defined.
	exportValueMappingElement7.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement7.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeStep.Description");
	exportValueMappingElement7.maxLength = 0;

	var exportObjectMappingElement1 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement1.elementType = mappings.ElementType.Wrapper;
	exportObjectMappingElement1.jsonPath = "(Object)|steps|(Wrapper)";
	exportObjectMappingElement1.maxOccurs = -1;
	exportObjectMappingElement1.nillable = true;
	exportObjectMappingElement1.exposedName = "Step";
	exportObjectMappingElement1.children.push(exportValueMappingElement7);
	exportObjectMappingElement1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeStep");
	exportObjectMappingElement1.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeStep");
	exportObjectMappingElement1.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement1.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var exportObjectMappingElement2 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement2.elementType = mappings.ElementType.Array;
	exportObjectMappingElement2.jsonPath = "(Object)|steps";
	exportObjectMappingElement2.maxOccurs = 1;
	exportObjectMappingElement2.nillable = true;
	exportObjectMappingElement2.exposedName = "Steps";
	exportObjectMappingElement2.children.push(exportObjectMappingElement1);
	exportObjectMappingElement2.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement2.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var stringType6 = datatypes.StringType.create(model);

	var exportValueMappingElement8 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement8.elementType = mappings.ElementType.Value;
	exportValueMappingElement8.jsonPath = "(Object)|ingredients|(Object)|name";
	exportValueMappingElement8.maxOccurs = 1;
	exportValueMappingElement8.nillable = true;
	exportValueMappingElement8.exposedName = "Name";
	exportValueMappingElement8.type = stringType6;   // Note: for this property a default value is defined.
	exportValueMappingElement8.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement8.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Name");
	exportValueMappingElement8.maxLength = 0;

	var decimalType1 = datatypes.DecimalType.create(model);

	var exportValueMappingElement9 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement9.elementType = mappings.ElementType.Value;
	exportValueMappingElement9.jsonPath = "(Object)|ingredients|(Object)|quantity";
	exportValueMappingElement9.maxOccurs = 1;
	exportValueMappingElement9.nillable = true;
	exportValueMappingElement9.exposedName = "Quantity";
	exportValueMappingElement9.type = decimalType1;   // Note: for this property a default value is defined.
	exportValueMappingElement9.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.Decimal;
	exportValueMappingElement9.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Quantity");

	var stringType7 = datatypes.StringType.create(model);

	var exportValueMappingElement10 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement10.elementType = mappings.ElementType.Value;
	exportValueMappingElement10.jsonPath = "(Object)|ingredients|(Object)|unit";
	exportValueMappingElement10.maxOccurs = 1;
	exportValueMappingElement10.nillable = true;
	exportValueMappingElement10.exposedName = "Unit";
	exportValueMappingElement10.type = stringType7;   // Note: for this property a default value is defined.
	exportValueMappingElement10.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement10.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Unit");
	exportValueMappingElement10.maxLength = 0;

	var exportObjectMappingElement3 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement3.elementType = mappings.ElementType.Object;
	exportObjectMappingElement3.jsonPath = "(Object)|ingredients|(Object)";
	exportObjectMappingElement3.maxOccurs = -1;
	exportObjectMappingElement3.nillable = true;
	exportObjectMappingElement3.exposedName = "Ingredient";
	exportObjectMappingElement3.children.push(exportValueMappingElement8);
	exportObjectMappingElement3.children.push(exportValueMappingElement9);
	exportObjectMappingElement3.children.push(exportValueMappingElement10);
	exportObjectMappingElement3.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeIngredient");
	exportObjectMappingElement3.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeIngredient");
	exportObjectMappingElement3.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement3.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var exportObjectMappingElement4 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement4.elementType = mappings.ElementType.Array;
	exportObjectMappingElement4.jsonPath = "(Object)|ingredients";
	exportObjectMappingElement4.maxOccurs = 1;
	exportObjectMappingElement4.nillable = true;
	exportObjectMappingElement4.exposedName = "Ingredients";
	exportObjectMappingElement4.children.push(exportObjectMappingElement3);
	exportObjectMappingElement4.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement4.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var stringType8 = datatypes.StringType.create(model);

	var exportValueMappingElement11 = exportmappings.ExportValueMappingElement.create(model);
	exportValueMappingElement11.elementType = mappings.ElementType.Value;
	exportValueMappingElement11.jsonPath = "(Object)|categories|(Wrapper)|(Value)";
	exportValueMappingElement11.maxOccurs = 1;
	exportValueMappingElement11.nillable = true;
	exportValueMappingElement11.exposedName = "Value";
	exportValueMappingElement11.type = stringType8;   // Note: for this property a default value is defined.
	exportValueMappingElement11.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	exportValueMappingElement11.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeCategory.Name");
	exportValueMappingElement11.maxLength = 0;

	var exportObjectMappingElement5 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement5.elementType = mappings.ElementType.Wrapper;
	exportObjectMappingElement5.jsonPath = "(Object)|categories|(Wrapper)";
	exportObjectMappingElement5.maxOccurs = -1;
	exportObjectMappingElement5.nillable = true;
	exportObjectMappingElement5.exposedName = "Category";
	exportObjectMappingElement5.children.push(exportValueMappingElement11);
	exportObjectMappingElement5.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeCategory");
	exportObjectMappingElement5.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeCategory");
	exportObjectMappingElement5.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement5.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var exportObjectMappingElement6 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement6.elementType = mappings.ElementType.Array;
	exportObjectMappingElement6.jsonPath = "(Object)|categories";
	exportObjectMappingElement6.maxOccurs = 1;
	exportObjectMappingElement6.nillable = true;
	exportObjectMappingElement6.exposedName = "Categories";
	exportObjectMappingElement6.children.push(exportObjectMappingElement5);
	exportObjectMappingElement6.objectHandling = mappings.ObjectHandlingEnum.Find;
	exportObjectMappingElement6.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Ignore;

	var exportObjectMappingElement7 = exportmappings.ExportObjectMappingElement.create(model);
	exportObjectMappingElement7.elementType = mappings.ElementType.Object;
	exportObjectMappingElement7.jsonPath = "(Object)";
	exportObjectMappingElement7.minOccurs = 1;
	exportObjectMappingElement7.maxOccurs = 1;
	exportObjectMappingElement7.nillable = true;
	exportObjectMappingElement7.exposedName = "Root";
	exportObjectMappingElement7.children.push(exportValueMappingElement1);
	exportObjectMappingElement7.children.push(exportValueMappingElement2);
	exportObjectMappingElement7.children.push(exportValueMappingElement3);
	exportObjectMappingElement7.children.push(exportValueMappingElement4);
	exportObjectMappingElement7.children.push(exportValueMappingElement5);
	exportObjectMappingElement7.children.push(exportValueMappingElement6);
	exportObjectMappingElement7.children.push(exportObjectMappingElement2);
	exportObjectMappingElement7.children.push(exportObjectMappingElement4);
	exportObjectMappingElement7.children.push(exportObjectMappingElement6);
	exportObjectMappingElement7.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");
	exportObjectMappingElement7.objectHandling = mappings.ObjectHandlingEnum.Parameter;
	exportObjectMappingElement7.objectHandlingBackup = mappings.ObjectHandlingBackupEnum.Error;

	var createRecipe_ExportMapping1 = exportmappings.ExportMapping.createIn(unit);
	createRecipe_ExportMapping1.name = "CreateRecipe_ExportMapping";
	createRecipe_ExportMapping1.rootMappingElements.push(exportObjectMappingElement7);
	createRecipe_ExportMapping1.jsonStructure = model.findJsonStructureByQualifiedName("MyFirstModule.CreateRecipe_Request");

})