(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "e2e245f5-834a-47f4-9c0a-4e3aba2bd49e" of type ImportMappings$ImportMapping
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var importValueMappingElement1 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement1.elementType = mappings.ElementType.Value;
	importValueMappingElement1.jsonPath = "(Object)|id";
	importValueMappingElement1.maxOccurs = 1;
	importValueMappingElement1.nillable = true;
	importValueMappingElement1.exposedName = "Id";
	importValueMappingElement1.type = stringType1;   // Note: for this property a default value is defined.
	importValueMappingElement1.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement1.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.RecipeId");
	importValueMappingElement1.maxLength = 0;

	var stringType2 = datatypes.StringType.create(model);

	var importValueMappingElement2 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement2.elementType = mappings.ElementType.Value;
	importValueMappingElement2.jsonPath = "(Object)|name";
	importValueMappingElement2.maxOccurs = 1;
	importValueMappingElement2.nillable = true;
	importValueMappingElement2.exposedName = "Name";
	importValueMappingElement2.type = stringType2;   // Note: for this property a default value is defined.
	importValueMappingElement2.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement2.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Name");
	importValueMappingElement2.maxLength = 0;

	var stringType3 = datatypes.StringType.create(model);

	var importValueMappingElement3 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement3.elementType = mappings.ElementType.Value;
	importValueMappingElement3.jsonPath = "(Object)|description";
	importValueMappingElement3.maxOccurs = 1;
	importValueMappingElement3.nillable = true;
	importValueMappingElement3.exposedName = "Description";
	importValueMappingElement3.type = stringType3;   // Note: for this property a default value is defined.
	importValueMappingElement3.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement3.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Description");
	importValueMappingElement3.maxLength = 0;

	var stringType4 = datatypes.StringType.create(model);

	var importValueMappingElement4 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement4.elementType = mappings.ElementType.Value;
	importValueMappingElement4.jsonPath = "(Object)|author";
	importValueMappingElement4.maxOccurs = 1;
	importValueMappingElement4.nillable = true;
	importValueMappingElement4.exposedName = "Author";
	importValueMappingElement4.type = stringType4;   // Note: for this property a default value is defined.
	importValueMappingElement4.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement4.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Author");
	importValueMappingElement4.maxLength = 0;

	var dateTimeType1 = datatypes.DateTimeType.create(model);

	var importValueMappingElement5 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement5.elementType = mappings.ElementType.Value;
	importValueMappingElement5.jsonPath = "(Object)|postedAt";
	importValueMappingElement5.maxOccurs = 1;
	importValueMappingElement5.nillable = true;
	importValueMappingElement5.exposedName = "PostedAt";
	importValueMappingElement5.type = dateTimeType1;   // Note: for this property a default value is defined.
	importValueMappingElement5.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.DateTime;
	importValueMappingElement5.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PostedAt");

	var stringType5 = datatypes.StringType.create(model);

	var importValueMappingElement6 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement6.elementType = mappings.ElementType.Value;
	importValueMappingElement6.jsonPath = "(Object)|postedTo";
	importValueMappingElement6.maxOccurs = 1;
	importValueMappingElement6.nillable = true;
	importValueMappingElement6.exposedName = "PostedTo";
	importValueMappingElement6.type = stringType5;   // Note: for this property a default value is defined.
	importValueMappingElement6.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement6.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PostedTo");
	importValueMappingElement6.maxLength = 0;

	var integerType1 = datatypes.IntegerType.create(model);

	var importValueMappingElement7 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement7.elementType = mappings.ElementType.Value;
	importValueMappingElement7.jsonPath = "(Object)|preparationTimeInMinutes";
	importValueMappingElement7.maxOccurs = 1;
	importValueMappingElement7.nillable = true;
	importValueMappingElement7.exposedName = "PreparationTimeInMinutes";
	importValueMappingElement7.type = integerType1;   // Note: for this property a default value is defined.
	importValueMappingElement7.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.Integer;
	importValueMappingElement7.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PreparationTimeInMinutes");

	var stringType6 = datatypes.StringType.create(model);

	var importValueMappingElement8 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement8.elementType = mappings.ElementType.Value;
	importValueMappingElement8.jsonPath = "(Object)|steps|(Wrapper)|(Value)";
	importValueMappingElement8.maxOccurs = 1;
	importValueMappingElement8.nillable = true;
	importValueMappingElement8.exposedName = "Value";
	importValueMappingElement8.type = stringType6;   // Note: for this property a default value is defined.
	importValueMappingElement8.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement8.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeStep.Description");
	importValueMappingElement8.maxLength = 0;

	var importObjectMappingElement1 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement1.elementType = mappings.ElementType.Wrapper;
	importObjectMappingElement1.jsonPath = "(Object)|steps|(Wrapper)";
	importObjectMappingElement1.maxOccurs = -1;
	importObjectMappingElement1.nillable = true;
	importObjectMappingElement1.exposedName = "Step";
	importObjectMappingElement1.children.push(importValueMappingElement8);
	importObjectMappingElement1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeStep");
	importObjectMappingElement1.association = model.findAssociationBaseByQualifiedName("MyFirstModule.RecipeStep_RecipeDetail");

	var stringType7 = datatypes.StringType.create(model);

	var importValueMappingElement9 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement9.elementType = mappings.ElementType.Value;
	importValueMappingElement9.jsonPath = "(Object)|ingredients|(Object)|name";
	importValueMappingElement9.maxOccurs = 1;
	importValueMappingElement9.nillable = true;
	importValueMappingElement9.exposedName = "Name";
	importValueMappingElement9.type = stringType7;   // Note: for this property a default value is defined.
	importValueMappingElement9.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement9.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Name");
	importValueMappingElement9.maxLength = 0;

	var decimalType1 = datatypes.DecimalType.create(model);

	var importValueMappingElement10 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement10.elementType = mappings.ElementType.Value;
	importValueMappingElement10.jsonPath = "(Object)|ingredients|(Object)|quantity";
	importValueMappingElement10.maxOccurs = 1;
	importValueMappingElement10.nillable = true;
	importValueMappingElement10.exposedName = "Quantity";
	importValueMappingElement10.type = decimalType1;   // Note: for this property a default value is defined.
	importValueMappingElement10.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.Decimal;
	importValueMappingElement10.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Quantity");

	var stringType8 = datatypes.StringType.create(model);

	var importValueMappingElement11 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement11.elementType = mappings.ElementType.Value;
	importValueMappingElement11.jsonPath = "(Object)|ingredients|(Object)|unit";
	importValueMappingElement11.maxOccurs = 1;
	importValueMappingElement11.nillable = true;
	importValueMappingElement11.exposedName = "Unit";
	importValueMappingElement11.type = stringType8;   // Note: for this property a default value is defined.
	importValueMappingElement11.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement11.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Unit");
	importValueMappingElement11.maxLength = 0;

	var importObjectMappingElement2 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement2.elementType = mappings.ElementType.Object;
	importObjectMappingElement2.jsonPath = "(Object)|ingredients|(Object)";
	importObjectMappingElement2.maxOccurs = -1;
	importObjectMappingElement2.nillable = true;
	importObjectMappingElement2.exposedName = "Ingredient";
	importObjectMappingElement2.children.push(importValueMappingElement9);
	importObjectMappingElement2.children.push(importValueMappingElement10);
	importObjectMappingElement2.children.push(importValueMappingElement11);
	importObjectMappingElement2.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeIngredient");
	importObjectMappingElement2.association = model.findAssociationBaseByQualifiedName("MyFirstModule.RecipeIngredient_RecipeDetail");

	var stringType9 = datatypes.StringType.create(model);

	var importValueMappingElement12 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement12.elementType = mappings.ElementType.Value;
	importValueMappingElement12.jsonPath = "(Object)|categories|(Wrapper)|(Value)";
	importValueMappingElement12.maxOccurs = 1;
	importValueMappingElement12.nillable = true;
	importValueMappingElement12.exposedName = "Value";
	importValueMappingElement12.type = stringType9;   // Note: for this property a default value is defined.
	importValueMappingElement12.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement12.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeCategory.Name");
	importValueMappingElement12.maxLength = 0;

	var importObjectMappingElement3 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement3.elementType = mappings.ElementType.Wrapper;
	importObjectMappingElement3.jsonPath = "(Object)|categories|(Wrapper)";
	importObjectMappingElement3.maxOccurs = -1;
	importObjectMappingElement3.nillable = true;
	importObjectMappingElement3.exposedName = "Category";
	importObjectMappingElement3.children.push(importValueMappingElement12);
	importObjectMappingElement3.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeCategory");
	importObjectMappingElement3.association = model.findAssociationBaseByQualifiedName("MyFirstModule.RecipeCategory_RecipeDetail");

	var importObjectMappingElement4 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement4.elementType = mappings.ElementType.Object;
	importObjectMappingElement4.jsonPath = "(Object)";
	importObjectMappingElement4.minOccurs = 1;
	importObjectMappingElement4.maxOccurs = 1;
	importObjectMappingElement4.nillable = true;
	importObjectMappingElement4.exposedName = "Root";
	importObjectMappingElement4.children.push(importValueMappingElement1);
	importObjectMappingElement4.children.push(importValueMappingElement2);
	importObjectMappingElement4.children.push(importValueMappingElement3);
	importObjectMappingElement4.children.push(importValueMappingElement4);
	importObjectMappingElement4.children.push(importValueMappingElement5);
	importObjectMappingElement4.children.push(importValueMappingElement6);
	importObjectMappingElement4.children.push(importValueMappingElement7);
	importObjectMappingElement4.children.push(importObjectMappingElement1);
	importObjectMappingElement4.children.push(importObjectMappingElement2);
	importObjectMappingElement4.children.push(importObjectMappingElement3);
	importObjectMappingElement4.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeDetail");

	var unknownType1 = datatypes.UnknownType.create(model);

	var recipe_ImportMapping1 = importmappings.ImportMapping.createIn(unit);
	recipe_ImportMapping1.name = "Recipe_ImportMapping";
	recipe_ImportMapping1.rootMappingElements.push(importObjectMappingElement4);
	recipe_ImportMapping1.jsonStructure = model.findJsonStructureByQualifiedName("MyFirstModule.Recipe_Response");
	recipe_ImportMapping1.parameterType = unknownType1;   // Note: for this property a default value is defined.

})