(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "1cd57393-0e78-4b94-bd4c-125ff2db8052" of type ImportMappings$ImportMapping
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var importValueMappingElement1 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement1.elementType = mappings.ElementType.Value;
	importValueMappingElement1.jsonPath = "(Object)|content|(Object)|id";
	importValueMappingElement1.maxOccurs = 1;
	importValueMappingElement1.nillable = true;
	importValueMappingElement1.exposedName = "_id";
	importValueMappingElement1.type = stringType1;   // Note: for this property a default value is defined.
	importValueMappingElement1.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement1.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.RecipeId");
	importValueMappingElement1.maxLength = 0;

	var stringType2 = datatypes.StringType.create(model);

	var importValueMappingElement2 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement2.elementType = mappings.ElementType.Value;
	importValueMappingElement2.jsonPath = "(Object)|content|(Object)|name";
	importValueMappingElement2.maxOccurs = 1;
	importValueMappingElement2.nillable = true;
	importValueMappingElement2.exposedName = "Name";
	importValueMappingElement2.type = stringType2;   // Note: for this property a default value is defined.
	importValueMappingElement2.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement2.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.Name");
	importValueMappingElement2.maxLength = 0;

	var stringType3 = datatypes.StringType.create(model);

	var importValueMappingElement3 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement3.elementType = mappings.ElementType.Value;
	importValueMappingElement3.jsonPath = "(Object)|content|(Object)|descriptionPrefix";
	importValueMappingElement3.maxOccurs = 1;
	importValueMappingElement3.nillable = true;
	importValueMappingElement3.exposedName = "DescriptionPrefix";
	importValueMappingElement3.type = stringType3;   // Note: for this property a default value is defined.
	importValueMappingElement3.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement3.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.DescriptionPrefix");
	importValueMappingElement3.maxLength = 0;

	var integerType1 = datatypes.IntegerType.create(model);

	var importValueMappingElement4 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement4.elementType = mappings.ElementType.Value;
	importValueMappingElement4.jsonPath = "(Object)|content|(Object)|preparationTimeInMinutes";
	importValueMappingElement4.maxOccurs = 1;
	importValueMappingElement4.nillable = true;
	importValueMappingElement4.exposedName = "PreparationTimeInMinutes";
	importValueMappingElement4.type = integerType1;   // Note: for this property a default value is defined.
	importValueMappingElement4.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.Integer;
	importValueMappingElement4.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.PreparationTimeInMinutes");

	var importObjectMappingElement1 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement1.elementType = mappings.ElementType.Object;
	importObjectMappingElement1.jsonPath = "(Object)|content|(Object)";
	importObjectMappingElement1.maxOccurs = -1;
	importObjectMappingElement1.nillable = true;
	importObjectMappingElement1.exposedName = "ContentItem";
	importObjectMappingElement1.children.push(importValueMappingElement1);
	importObjectMappingElement1.children.push(importValueMappingElement2);
	importObjectMappingElement1.children.push(importValueMappingElement3);
	importObjectMappingElement1.children.push(importValueMappingElement4);
	importObjectMappingElement1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeSummary");

	var unknownType1 = datatypes.UnknownType.create(model);

	var recipes_ImportMapping1 = importmappings.ImportMapping.createIn(unit);
	recipes_ImportMapping1.name = "Recipes_ImportMapping";
	recipes_ImportMapping1.rootMappingElements.push(importObjectMappingElement1);
	recipes_ImportMapping1.jsonStructure = model.findJsonStructureByQualifiedName("MyFirstModule.Recipes_Response");
	recipes_ImportMapping1.parameterType = unknownType1;   // Note: for this property a default value is defined.

})