(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "16bdb143-3ea7-415c-badb-7e6096383b53" of type ImportMappings$ImportMapping
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var stringType1 = datatypes.StringType.create(model);

	var importValueMappingElement1 = importmappings.ImportValueMappingElement.create(model);
	importValueMappingElement1.elementType = mappings.ElementType.Value;
	importValueMappingElement1.jsonPath = "(Array)|(Wrapper)|(Value)";
	importValueMappingElement1.maxOccurs = 1;
	importValueMappingElement1.nillable = true;
	importValueMappingElement1.exposedName = "Value";
	importValueMappingElement1.type = stringType1;   // Note: for this property a default value is defined.
	importValueMappingElement1.xmlPrimitiveType = xmlschemas.XmlPrimitiveType.String;
	importValueMappingElement1.attribute = model.findAttributeByQualifiedName("MyFirstModule.Category.Name");
	importValueMappingElement1.maxLength = 0;

	var importObjectMappingElement1 = importmappings.ImportObjectMappingElement.create(model);
	importObjectMappingElement1.elementType = mappings.ElementType.Wrapper;
	importObjectMappingElement1.jsonPath = "(Array)|(Wrapper)";
	importObjectMappingElement1.maxOccurs = -1;
	importObjectMappingElement1.nillable = true;
	importObjectMappingElement1.exposedName = "Wrapper";
	importObjectMappingElement1.children.push(importValueMappingElement1);
	importObjectMappingElement1.entity = model.findEntityByQualifiedName("MyFirstModule.Category");

	var unknownType1 = datatypes.UnknownType.create(model);

	var categories_ImportMapping1 = importmappings.ImportMapping.createIn(unit);
	categories_ImportMapping1.name = "Categories_ImportMapping";
	categories_ImportMapping1.rootMappingElements.push(importObjectMappingElement1);
	categories_ImportMapping1.jsonStructure = model.findJsonStructureByQualifiedName("MyFirstModule.Categories_Response");
	categories_ImportMapping1.parameterType = unknownType1;   // Note: for this property a default value is defined.

})