(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "5f5f75d8-ff54-4743-8e65-97099d92cf7b" of type JsonStructures$JsonStructure
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var jsonElement1 = jsonstructures.JsonElement.create(model);
	jsonElement1.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement1.path = "(Object)|content|(Object)|id";
	jsonElement1.minOccurs = 0;
	jsonElement1.nillable = true;
	jsonElement1.exposedName = "Id";
	jsonElement1.maxLength = 0;
	jsonElement1.originalValue = "\"205d4bc2-8f38-4a1e-9a1a-2c0f5a2d5f11\"";

	var jsonElement2 = jsonstructures.JsonElement.create(model);
	jsonElement2.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement2.path = "(Object)|content|(Object)|name";
	jsonElement2.minOccurs = 0;
	jsonElement2.nillable = true;
	jsonElement2.exposedName = "Name";
	jsonElement2.maxLength = 0;
	jsonElement2.originalValue = "\"30 Minute Chili\"";

	var jsonElement3 = jsonstructures.JsonElement.create(model);
	jsonElement3.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement3.path = "(Object)|content|(Object)|descriptionPrefix";
	jsonElement3.minOccurs = 0;
	jsonElement3.nillable = true;
	jsonElement3.exposedName = "DescriptionPrefix";
	jsonElement3.maxLength = 0;
	jsonElement3.originalValue = "\"Makes 6 servings\"";

	var jsonElement4 = jsonstructures.JsonElement.create(model);
	jsonElement4.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement4.path = "(Object)|content|(Object)|preparationTimeInMinutes";
	jsonElement4.minOccurs = 0;
	jsonElement4.nillable = true;
	jsonElement4.exposedName = "PreparationTimeInMinutes";
	jsonElement4.originalValue = "30";

	var jsonElement5 = jsonstructures.JsonElement.create(model);
	jsonElement5.elementType = mappings.ElementType.Object;
	jsonElement5.path = "(Object)|content|(Object)";
	jsonElement5.minOccurs = 0;
	jsonElement5.maxOccurs = -1;
	jsonElement5.nillable = true;
	jsonElement5.exposedName = "ContentItem";
	jsonElement5.children.push(jsonElement1);
	jsonElement5.children.push(jsonElement2);
	jsonElement5.children.push(jsonElement3);
	jsonElement5.children.push(jsonElement4);

	var jsonElement6 = jsonstructures.JsonElement.create(model);
	jsonElement6.elementType = mappings.ElementType.Array;
	jsonElement6.path = "(Object)|content";
	jsonElement6.minOccurs = 0;
	jsonElement6.nillable = true;
	jsonElement6.exposedName = "Content";
	jsonElement6.children.push(jsonElement5);

	var jsonElement7 = jsonstructures.JsonElement.create(model);
	jsonElement7.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement7.path = "(Object)|page|size";
	jsonElement7.minOccurs = 0;
	jsonElement7.nillable = true;
	jsonElement7.exposedName = "Size";
	jsonElement7.originalValue = "20";

	var jsonElement8 = jsonstructures.JsonElement.create(model);
	jsonElement8.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement8.path = "(Object)|page|number";
	jsonElement8.minOccurs = 0;
	jsonElement8.nillable = true;
	jsonElement8.exposedName = "Number";
	jsonElement8.originalValue = "0";

	var jsonElement9 = jsonstructures.JsonElement.create(model);
	jsonElement9.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement9.path = "(Object)|page|totalElements";
	jsonElement9.minOccurs = 0;
	jsonElement9.nillable = true;
	jsonElement9.exposedName = "TotalElements";
	jsonElement9.originalValue = "3";

	var jsonElement10 = jsonstructures.JsonElement.create(model);
	jsonElement10.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement10.path = "(Object)|page|totalPages";
	jsonElement10.minOccurs = 0;
	jsonElement10.nillable = true;
	jsonElement10.exposedName = "TotalPages";
	jsonElement10.originalValue = "1";

	var jsonElement11 = jsonstructures.JsonElement.create(model);
	jsonElement11.elementType = mappings.ElementType.Object;
	jsonElement11.path = "(Object)|page";
	jsonElement11.minOccurs = 0;
	jsonElement11.nillable = true;
	jsonElement11.exposedName = "Page";
	jsonElement11.children.push(jsonElement7);
	jsonElement11.children.push(jsonElement8);
	jsonElement11.children.push(jsonElement9);
	jsonElement11.children.push(jsonElement10);

	var jsonElement12 = jsonstructures.JsonElement.create(model);
	jsonElement12.elementType = mappings.ElementType.Object;
	jsonElement12.path = "(Object)";
	jsonElement12.nillable = true;
	jsonElement12.exposedName = "Root";
	jsonElement12.children.push(jsonElement6);
	jsonElement12.children.push(jsonElement11);

	var recipes_Response1 = jsonstructures.JsonStructure.createIn(unit);
	recipes_Response1.name = "Recipes_Response";
	recipes_Response1.jsonSnippet = "{\r\n    \"content\": [\r\n        {\r\n            \"id\": \"205d4bc2-8f38-4a1e-9a1a-2c0f5a2d5f11\",\r\n            \"name\": \"30 Minute Chili\",\r\n            \"descriptionPrefix\": \"Makes 6 servings\",\r\n            \"preparationTimeInMinutes\": 30\r\n        }\r\n    ],\r\n    \"page\": {\r\n        \"size\": 20,\r\n        \"number\": 0,\r\n        \"totalElements\": 3,\r\n        \"totalPages\": 1\r\n    }\r\n}";
	recipes_Response1.elements.push(jsonElement12);

})