(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "bba1e854-8e01-4cf8-a2d4-90e1eb02a680" of type JsonStructures$JsonStructure
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var jsonElement1 = jsonstructures.JsonElement.create(model);
	jsonElement1.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement1.path = "(Object)|name";
	jsonElement1.minOccurs = 0;
	jsonElement1.nillable = true;
	jsonElement1.exposedName = "Name";
	jsonElement1.maxLength = 0;
	jsonElement1.originalValue = "\"30 Minute Chili\"";

	var jsonElement2 = jsonstructures.JsonElement.create(model);
	jsonElement2.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement2.path = "(Object)|description";
	jsonElement2.minOccurs = 0;
	jsonElement2.nillable = true;
	jsonElement2.exposedName = "Description";
	jsonElement2.maxLength = 0;
	jsonElement2.originalValue = "\"A quick chili that is ready in half an hour.\"";

	var jsonElement3 = jsonstructures.JsonElement.create(model);
	jsonElement3.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement3.path = "(Object)|steps|(Wrapper)|(Value)";
	jsonElement3.minOccurs = 0;
	jsonElement3.nillable = true;
	jsonElement3.exposedName = "Value";
	jsonElement3.maxLength = 0;
	jsonElement3.originalValue = "\"Brown the ground beef in a large pot.\"";

	var jsonElement4 = jsonstructures.JsonElement.create(model);
	jsonElement4.elementType = mappings.ElementType.Wrapper;
	jsonElement4.path = "(Object)|steps|(Wrapper)";
	jsonElement4.minOccurs = 0;
	jsonElement4.maxOccurs = -1;
	jsonElement4.nillable = true;
	jsonElement4.exposedName = "Step";
	jsonElement4.children.push(jsonElement3);

	var jsonElement5 = jsonstructures.JsonElement.create(model);
	jsonElement5.elementType = mappings.ElementType.Array;
	jsonElement5.path = "(Object)|steps";
	jsonElement5.minOccurs = 0;
	jsonElement5.nillable = true;
	jsonElement5.exposedName = "Steps";
	jsonElement5.children.push(jsonElement4);

	var jsonElement6 = jsonstructures.JsonElement.create(model);
	jsonElement6.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement6.path = "(Object)|ingredients|(Object)|name";
	jsonElement6.minOccurs = 0;
	jsonElement6.nillable = true;
	jsonElement6.exposedName = "Name";
	jsonElement6.maxLength = 0;
	jsonElement6.originalValue = "\"ground beef\"";

	var jsonElement7 = jsonstructures.JsonElement.create(model);
	jsonElement7.primitiveType = xmlschemas.XmlPrimitiveType.Decimal;
	jsonElement7.path = "(Object)|ingredients|(Object)|quantity";
	jsonElement7.minOccurs = 0;
	jsonElement7.nillable = true;
	jsonElement7.exposedName = "Quantity";
	jsonElement7.originalValue = "1.5";

	var jsonElement8 = jsonstructures.JsonElement.create(model);
	jsonElement8.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement8.path = "(Object)|ingredients|(Object)|unit";
	jsonElement8.minOccurs = 0;
	jsonElement8.nillable = true;
	jsonElement8.exposedName = "Unit";
	jsonElement8.maxLength = 0;
	jsonElement8.originalValue = "\"POUND\"";

	var jsonElement9 = jsonstructures.JsonElement.create(model);
	jsonElement9.elementType = mappings.ElementType.Object;
	jsonElement9.path = "(Object)|ingredients|(Object)";
	jsonElement9.minOccurs = 0;
	jsonElement9.maxOccurs = -1;
	jsonElement9.nillable = true;
	jsonElement9.exposedName = "Ingredient";
	jsonElement9.children.push(jsonElement6);
	jsonElement9.children.push(jsonElement7);
	jsonElement9.children.push(jsonElement8);

	var jsonElement10 = jsonstructures.JsonElement.create(model);
	jsonElement10.elementType = mappings.ElementType.Array;
	jsonElement10.path = "(Object)|ingredients";
	jsonElement10.minOccurs = 0;
	jsonElement10.nillable = true;
	jsonElement10.exposedName = "Ingredients";
	jsonElement10.children.push(jsonElement9);

	var jsonElement11 = jsonstructures.JsonElement.create(model);
	jsonElement11.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement11.path = "(Object)|author";
	jsonElement11.minOccurs = 0;
	jsonElement11.nillable = true;
	jsonElement11.exposedName = "Author";
	jsonElement11.maxLength = 0;
	jsonElement11.originalValue = "\"Unknown\"";

	var jsonElement12 = jsonstructures.JsonElement.create(model);
	jsonElement12.primitiveType = xmlschemas.XmlPrimitiveType.DateTime;
	jsonElement12.path = "(Object)|postedAt";
	jsonElement12.minOccurs = 0;
	jsonElement12.nillable = true;
	jsonElement12.exposedName = "PostedAt";
	jsonElement12.originalValue = "\"2026-09-10T20:34:28.0840000Z\"";

	var jsonElement13 = jsonstructures.JsonElement.create(model);
	jsonElement13.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement13.path = "(Object)|postedTo";
	jsonElement13.minOccurs = 0;
	jsonElement13.nillable = true;
	jsonElement13.exposedName = "PostedTo";
	jsonElement13.maxLength = 0;
	jsonElement13.originalValue = "\"Mendix app\"";

	var jsonElement14 = jsonstructures.JsonElement.create(model);
	jsonElement14.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement14.path = "(Object)|preparationTimeInMinutes";
	jsonElement14.minOccurs = 0;
	jsonElement14.nillable = true;
	jsonElement14.exposedName = "PreparationTimeInMinutes";
	jsonElement14.originalValue = "30";

	var jsonElement15 = jsonstructures.JsonElement.create(model);
	jsonElement15.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement15.path = "(Object)|categories|(Wrapper)|(Value)";
	jsonElement15.minOccurs = 0;
	jsonElement15.nillable = true;
	jsonElement15.exposedName = "Value";
	jsonElement15.maxLength = 0;
	jsonElement15.originalValue = "\"chili\"";

	var jsonElement16 = jsonstructures.JsonElement.create(model);
	jsonElement16.elementType = mappings.ElementType.Wrapper;
	jsonElement16.path = "(Object)|categories|(Wrapper)";
	jsonElement16.minOccurs = 0;
	jsonElement16.maxOccurs = -1;
	jsonElement16.nillable = true;
	jsonElement16.exposedName = "Category";
	jsonElement16.children.push(jsonElement15);

	var jsonElement17 = jsonstructures.JsonElement.create(model);
	jsonElement17.elementType = mappings.ElementType.Array;
	jsonElement17.path = "(Object)|categories";
	jsonElement17.minOccurs = 0;
	jsonElement17.nillable = true;
	jsonElement17.exposedName = "Categories";
	jsonElement17.children.push(jsonElement16);

	var jsonElement18 = jsonstructures.JsonElement.create(model);
	jsonElement18.elementType = mappings.ElementType.Object;
	jsonElement18.path = "(Object)";
	jsonElement18.nillable = true;
	jsonElement18.exposedName = "Root";
	jsonElement18.children.push(jsonElement1);
	jsonElement18.children.push(jsonElement2);
	jsonElement18.children.push(jsonElement5);
	jsonElement18.children.push(jsonElement10);
	jsonElement18.children.push(jsonElement11);
	jsonElement18.children.push(jsonElement12);
	jsonElement18.children.push(jsonElement13);
	jsonElement18.children.push(jsonElement14);
	jsonElement18.children.push(jsonElement17);

	var createRecipe_Request1 = jsonstructures.JsonStructure.createIn(unit);
	createRecipe_Request1.name = "CreateRecipe_Request";
	createRecipe_Request1.jsonSnippet = "{\r\n    \"name\": \"30 Minute Chili\",\r\n    \"description\": \"A quick chili that is ready in half an hour.\",\r\n    \"steps\": [\r\n        \"Brown the ground beef in a large pot.\"\r\n    ],\r\n    \"ingredients\": [\r\n        {\r\n            \"name\": \"ground beef\",\r\n            \"quantity\": 1.5,\r\n            \"unit\": \"POUND\"\r\n        }\r\n    ],\r\n    \"author\": \"Unknown\",\r\n    \"postedAt\": \"2026-09-10T20:34:28.084Z\",\r\n    \"postedTo\": \"Mendix app\",\r\n    \"preparationTimeInMinutes\": 30,\r\n    \"categories\": [\r\n        \"chili\"\r\n    ]\r\n}";
	createRecipe_Request1.elements.push(jsonElement18);

})