(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "42358182-b273-489b-9bb9-7f9d2a08efbb" of type JsonStructures$JsonStructure
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var jsonElement1 = jsonstructures.JsonElement.create(model);
	jsonElement1.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement1.path = "(Object)|id";
	jsonElement1.minOccurs = 0;
	jsonElement1.nillable = true;
	jsonElement1.exposedName = "Id";
	jsonElement1.maxLength = 0;
	jsonElement1.originalValue = "\"205d4bc2-8f38-4a1e-9a1a-2c0f5a2d5f11\"";

	var jsonElement2 = jsonstructures.JsonElement.create(model);
	jsonElement2.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement2.path = "(Object)|name";
	jsonElement2.minOccurs = 0;
	jsonElement2.nillable = true;
	jsonElement2.exposedName = "Name";
	jsonElement2.maxLength = 0;
	jsonElement2.originalValue = "\"30 Minute Chili\"";

	var jsonElement3 = jsonstructures.JsonElement.create(model);
	jsonElement3.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement3.path = "(Object)|description";
	jsonElement3.minOccurs = 0;
	jsonElement3.nillable = true;
	jsonElement3.exposedName = "Description";
	jsonElement3.maxLength = 0;
	jsonElement3.originalValue = "\"Makes 6 servings. A quick chili that is ready in half an hour.\"";

	var jsonElement4 = jsonstructures.JsonElement.create(model);
	jsonElement4.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement4.path = "(Object)|steps|(Wrapper)|(Value)";
	jsonElement4.minOccurs = 0;
	jsonElement4.nillable = true;
	jsonElement4.exposedName = "Value";
	jsonElement4.maxLength = 0;
	jsonElement4.originalValue = "\"Brown the ground beef in a large pot.\"";

	var jsonElement5 = jsonstructures.JsonElement.create(model);
	jsonElement5.elementType = mappings.ElementType.Wrapper;
	jsonElement5.path = "(Object)|steps|(Wrapper)";
	jsonElement5.minOccurs = 0;
	jsonElement5.maxOccurs = -1;
	jsonElement5.nillable = true;
	jsonElement5.exposedName = "Step";
	jsonElement5.children.push(jsonElement4);

	var jsonElement6 = jsonstructures.JsonElement.create(model);
	jsonElement6.elementType = mappings.ElementType.Array;
	jsonElement6.path = "(Object)|steps";
	jsonElement6.minOccurs = 0;
	jsonElement6.nillable = true;
	jsonElement6.exposedName = "Steps";
	jsonElement6.children.push(jsonElement5);

	var jsonElement7 = jsonstructures.JsonElement.create(model);
	jsonElement7.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement7.path = "(Object)|ingredients|(Object)|name";
	jsonElement7.minOccurs = 0;
	jsonElement7.nillable = true;
	jsonElement7.exposedName = "Name";
	jsonElement7.maxLength = 0;
	jsonElement7.originalValue = "\"ground beef\"";

	var jsonElement8 = jsonstructures.JsonElement.create(model);
	jsonElement8.primitiveType = xmlschemas.XmlPrimitiveType.Decimal;
	jsonElement8.path = "(Object)|ingredients|(Object)|quantity";
	jsonElement8.minOccurs = 0;
	jsonElement8.nillable = true;
	jsonElement8.exposedName = "Quantity";
	jsonElement8.originalValue = "1.5";

	var jsonElement9 = jsonstructures.JsonElement.create(model);
	jsonElement9.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement9.path = "(Object)|ingredients|(Object)|unit";
	jsonElement9.minOccurs = 0;
	jsonElement9.nillable = true;
	jsonElement9.exposedName = "Unit";
	jsonElement9.maxLength = 0;
	jsonElement9.originalValue = "\"POUND\"";

	var jsonElement10 = jsonstructures.JsonElement.create(model);
	jsonElement10.elementType = mappings.ElementType.Object;
	jsonElement10.path = "(Object)|ingredients|(Object)";
	jsonElement10.minOccurs = 0;
	jsonElement10.maxOccurs = -1;
	jsonElement10.nillable = true;
	jsonElement10.exposedName = "Ingredient";
	jsonElement10.children.push(jsonElement7);
	jsonElement10.children.push(jsonElement8);
	jsonElement10.children.push(jsonElement9);

	var jsonElement11 = jsonstructures.JsonElement.create(model);
	jsonElement11.elementType = mappings.ElementType.Array;
	jsonElement11.path = "(Object)|ingredients";
	jsonElement11.minOccurs = 0;
	jsonElement11.nillable = true;
	jsonElement11.exposedName = "Ingredients";
	jsonElement11.children.push(jsonElement10);

	var jsonElement12 = jsonstructures.JsonElement.create(model);
	jsonElement12.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement12.path = "(Object)|author";
	jsonElement12.minOccurs = 0;
	jsonElement12.nillable = true;
	jsonElement12.exposedName = "Author";
	jsonElement12.maxLength = 0;
	jsonElement12.originalValue = "\"Unknown\"";

	var jsonElement13 = jsonstructures.JsonElement.create(model);
	jsonElement13.primitiveType = xmlschemas.XmlPrimitiveType.DateTime;
	jsonElement13.path = "(Object)|postedAt";
	jsonElement13.minOccurs = 0;
	jsonElement13.nillable = true;
	jsonElement13.exposedName = "PostedAt";
	jsonElement13.originalValue = "\"2026-09-10T20:34:28.0840000Z\"";

	var jsonElement14 = jsonstructures.JsonElement.create(model);
	jsonElement14.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement14.path = "(Object)|postedTo";
	jsonElement14.minOccurs = 0;
	jsonElement14.nillable = true;
	jsonElement14.exposedName = "PostedTo";
	jsonElement14.maxLength = 0;
	jsonElement14.originalValue = "\"seed data\"";

	var jsonElement15 = jsonstructures.JsonElement.create(model);
	jsonElement15.primitiveType = xmlschemas.XmlPrimitiveType.Integer;
	jsonElement15.path = "(Object)|preparationTimeInMinutes";
	jsonElement15.minOccurs = 0;
	jsonElement15.nillable = true;
	jsonElement15.exposedName = "PreparationTimeInMinutes";
	jsonElement15.originalValue = "30";

	var jsonElement16 = jsonstructures.JsonElement.create(model);
	jsonElement16.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement16.path = "(Object)|categories|(Wrapper)|(Value)";
	jsonElement16.minOccurs = 0;
	jsonElement16.nillable = true;
	jsonElement16.exposedName = "Value";
	jsonElement16.maxLength = 0;
	jsonElement16.originalValue = "\"chili\"";

	var jsonElement17 = jsonstructures.JsonElement.create(model);
	jsonElement17.elementType = mappings.ElementType.Wrapper;
	jsonElement17.path = "(Object)|categories|(Wrapper)";
	jsonElement17.minOccurs = 0;
	jsonElement17.maxOccurs = -1;
	jsonElement17.nillable = true;
	jsonElement17.exposedName = "Category";
	jsonElement17.children.push(jsonElement16);

	var jsonElement18 = jsonstructures.JsonElement.create(model);
	jsonElement18.elementType = mappings.ElementType.Array;
	jsonElement18.path = "(Object)|categories";
	jsonElement18.minOccurs = 0;
	jsonElement18.nillable = true;
	jsonElement18.exposedName = "Categories";
	jsonElement18.children.push(jsonElement17);

	var jsonElement19 = jsonstructures.JsonElement.create(model);
	jsonElement19.elementType = mappings.ElementType.Object;
	jsonElement19.path = "(Object)";
	jsonElement19.nillable = true;
	jsonElement19.exposedName = "Root";
	jsonElement19.children.push(jsonElement1);
	jsonElement19.children.push(jsonElement2);
	jsonElement19.children.push(jsonElement3);
	jsonElement19.children.push(jsonElement6);
	jsonElement19.children.push(jsonElement11);
	jsonElement19.children.push(jsonElement12);
	jsonElement19.children.push(jsonElement13);
	jsonElement19.children.push(jsonElement14);
	jsonElement19.children.push(jsonElement15);
	jsonElement19.children.push(jsonElement18);

	var recipe_Response1 = jsonstructures.JsonStructure.createIn(unit);
	recipe_Response1.name = "Recipe_Response";
	recipe_Response1.jsonSnippet = "{\r\n    \"id\": \"205d4bc2-8f38-4a1e-9a1a-2c0f5a2d5f11\",\r\n    \"name\": \"30 Minute Chili\",\r\n    \"description\": \"Makes 6 servings. A quick chili that is ready in half an hour.\",\r\n    \"steps\": [\r\n        \"Brown the ground beef in a large pot.\",\r\n        \"Add the remaining ingredients and simmer for 20 minutes.\"\r\n    ],\r\n    \"ingredients\": [\r\n        {\r\n            \"name\": \"ground beef\",\r\n            \"quantity\": 1.5,\r\n            \"unit\": \"POUND\"\r\n        }\r\n    ],\r\n    \"author\": \"Unknown\",\r\n    \"postedAt\": \"2026-09-10T20:34:28.084Z\",\r\n    \"postedTo\": \"seed data\",\r\n    \"preparationTimeInMinutes\": 30,\r\n    \"categories\": [\r\n        \"chili\",\r\n        \"main dish\"\r\n    ]\r\n}";
	recipe_Response1.elements.push(jsonElement19);

})