(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "9d40ddd0-54a9-4a42-bee9-ad2743d418a1" of type JsonStructures$JsonStructure
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var jsonElement1 = jsonstructures.JsonElement.create(model);
	jsonElement1.primitiveType = xmlschemas.XmlPrimitiveType.String;
	jsonElement1.path = "(Array)|(Wrapper)|(Value)";
	jsonElement1.minOccurs = 0;
	jsonElement1.nillable = true;
	jsonElement1.exposedName = "Value";
	jsonElement1.maxLength = 0;
	jsonElement1.originalValue = "\"cake mixes\"";

	var jsonElement2 = jsonstructures.JsonElement.create(model);
	jsonElement2.elementType = mappings.ElementType.Wrapper;
	jsonElement2.path = "(Array)|(Wrapper)";
	jsonElement2.minOccurs = 0;
	jsonElement2.maxOccurs = -1;
	jsonElement2.nillable = true;
	jsonElement2.exposedName = "Wrapper";
	jsonElement2.children.push(jsonElement1);

	var jsonElement3 = jsonstructures.JsonElement.create(model);
	jsonElement3.elementType = mappings.ElementType.Array;
	jsonElement3.path = "(Array)";
	jsonElement3.nillable = true;
	jsonElement3.exposedName = "Root";
	jsonElement3.children.push(jsonElement2);

	var categories_Response1 = jsonstructures.JsonStructure.createIn(unit);
	categories_Response1.name = "Categories_Response";
	categories_Response1.jsonSnippet = "[\r\n    \"cake mixes\",\r\n    \"cakes\",\r\n    \"chili\"\r\n]";
	categories_Response1.elements.push(jsonElement3);

})