(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "842f40f9-f6c2-4e7d-9030-e0f317036089" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.Category");

	var category1 = microflows.MicroflowParameterObject.create(model);
	category1.relativeMiddlePoint = {"x":60,"y":0};
	category1.size = {"width":30,"height":30};
	category1.name = "Category";
	category1.variableType = objectType1;   // Note: for this property a default value is defined.

	var objectType2 = datatypes.ObjectType.create(model);
	objectType2.entity = model.findEntityByQualifiedName("MyFirstModule.HomeContext");

	var homeContext1 = microflows.MicroflowParameterObject.create(model);
	homeContext1.relativeMiddlePoint = {"x":220,"y":0};
	homeContext1.size = {"width":30,"height":30};
	homeContext1.name = "HomeContext";
	homeContext1.variableType = objectType2;   // Note: for this property a default value is defined.

	var memberChange1 = microflows.MemberChange.create(model);
	memberChange1.attribute = model.findAttributeByQualifiedName("MyFirstModule.HomeContext.SelectedCategory");
	memberChange1.value = "$Category/Name";

	var changeObjectAction1 = microflows.ChangeObjectAction.create(model);
	changeObjectAction1.items.push(memberChange1);
	changeObjectAction1.refreshInClient = true;
	changeObjectAction1.changeVariableName = "HomeContext";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":200,"height":60};
	actionActivity1.action = changeObjectAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":500,"y":120};
	endEvent1.size = {"width":20,"height":20};

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(category1);
	microflowObjectCollection1.objects.push(homeContext1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var voidType1 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var aCT_SelectCategory1 = microflows.Microflow.createIn(unit);
	aCT_SelectCategory1.name = "ACT_SelectCategory";
	aCT_SelectCategory1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	aCT_SelectCategory1.flows.push(sequenceFlow1);
	aCT_SelectCategory1.flows.push(sequenceFlow2);
	aCT_SelectCategory1.microflowReturnType = voidType1;
	aCT_SelectCategory1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	aCT_SelectCategory1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = endEvent1;

})