(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "18a38fc5-77e1-42d4-9f1b-3ea3b2d57db2" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeSummary");

	var recipeSummary1 = microflows.MicroflowParameterObject.create(model);
	recipeSummary1.relativeMiddlePoint = {"x":60,"y":0};
	recipeSummary1.size = {"width":30,"height":30};
	recipeSummary1.name = "RecipeSummary";
	recipeSummary1.variableType = objectType1;   // Note: for this property a default value is defined.

	var stringType1 = datatypes.StringType.create(model);

	var createVariableAction1 = microflows.CreateVariableAction.create(model);
	createVariableAction1.variableName = "Url";
	createVariableAction1.variableType = stringType1;   // Note: for this property a default value is defined.
	createVariableAction1.initialValue = "@MyFirstModule.RecipesApiBaseUrl + '/v1/recipes/' + $RecipeSummary/RecipeId";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":190,"height":60};
	actionActivity1.action = createVariableAction1;

	var templateArgument1 = microflows.TemplateArgument.create(model);
	templateArgument1.expression = "$Url";

	var stringTemplate1 = microflows.StringTemplate.create(model);
	stringTemplate1.arguments.push(templateArgument1);
	stringTemplate1.text = "{1}";

	var httpConfiguration1 = microflows.HttpConfiguration.create(model);
	httpConfiguration1.overrideLocation = true;
	httpConfiguration1.customLocationTemplate = stringTemplate1;
	httpConfiguration1.newHttpMethod = services.HttpMethod.Get;

	var stringTemplate2 = microflows.StringTemplate.create(model);

	var customRequestHandling1 = microflows.CustomRequestHandling.create(model);
	customRequestHandling1.template = stringTemplate2;   // Note: for this property a default value is defined.

	var constantRange1 = microflows.ConstantRange.create(model);
	constantRange1.singleObject = true;

	var importMappingCall1 = microflows.ImportMappingCall.create(model);
	importMappingCall1.mapping = model.findImportMappingByQualifiedName("MyFirstModule.Recipe_ImportMapping");
	importMappingCall1.range = constantRange1;   // Note: for this property a default value is defined.

	var objectType2 = datatypes.ObjectType.create(model);
	objectType2.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeDetail");

	var resultHandling1 = microflows.ResultHandling.create(model);
	resultHandling1.importMappingCall = importMappingCall1;
	resultHandling1.storeInVariable = true;
	resultHandling1.outputVariableName = "RecipeDetail";
	resultHandling1.variableType = objectType2;   // Note: for this property a default value is defined.

	var restCallAction1 = microflows.RestCallAction.create(model);
	restCallAction1.httpConfiguration = httpConfiguration1;   // Note: for this property a default value is defined.
	restCallAction1.requestHandling = customRequestHandling1;   // Note: for this property a default value is defined.
	restCallAction1.resultHandling = resultHandling1;   // Note: for this property a default value is defined.
	restCallAction1.resultHandlingType = microflows.ResultHandlingType.Mapping;

	var actionActivity2 = microflows.ActionActivity.create(model);
	actionActivity2.relativeMiddlePoint = {"x":500,"y":120};
	actionActivity2.size = {"width":190,"height":60};
	actionActivity2.action = restCallAction1;

	var pageVariable1 = pages.PageVariable.create(model);

	var pageParameterMapping1 = pages.PageParameterMapping.create(model);
	pageParameterMapping1.parameter = model.findPageParameterByQualifiedName("MyFirstModule.Recipe_Detail.RecipeDetail");
	pageParameterMapping1.variable = pageVariable1;
	pageParameterMapping1.argument = "$RecipeDetail";

	var pageSettings1 = pages.PageSettings.create(model);
	pageSettings1.page = model.findPageByQualifiedName("MyFirstModule.Recipe_Detail");
	pageSettings1.parameterMappings.push(pageParameterMapping1);

	var showPageAction1 = microflows.ShowPageAction.create(model);
	showPageAction1.pageSettings = pageSettings1;   // Note: for this property a default value is defined.

	var actionActivity3 = microflows.ActionActivity.create(model);
	actionActivity3.relativeMiddlePoint = {"x":720,"y":120};
	actionActivity3.size = {"width":210,"height":60};
	actionActivity3.action = showPageAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":940,"y":120};
	endEvent1.size = {"width":20,"height":20};

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(recipeSummary1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(actionActivity2);
	microflowObjectCollection1.objects.push(actionActivity3);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var bezierCurve3 = microflows.BezierCurve.create(model);
	bezierCurve3.originControlVector = {"width":30,"height":0};
	bezierCurve3.destinationControlVector = {"width":-30,"height":0};

	var noCase3 = microflows.NoCase.create(model);

	var sequenceFlow3 = microflows.SequenceFlow.create(model);
	sequenceFlow3.originConnectionIndex = 1;
	sequenceFlow3.destinationConnectionIndex = 3;
	sequenceFlow3.line = bezierCurve3;   // Note: for this property a default value is defined.
	sequenceFlow3.caseValues.push(noCase3);

	var bezierCurve4 = microflows.BezierCurve.create(model);
	bezierCurve4.originControlVector = {"width":30,"height":0};
	bezierCurve4.destinationControlVector = {"width":-30,"height":0};

	var noCase4 = microflows.NoCase.create(model);

	var sequenceFlow4 = microflows.SequenceFlow.create(model);
	sequenceFlow4.originConnectionIndex = 1;
	sequenceFlow4.destinationConnectionIndex = 3;
	sequenceFlow4.line = bezierCurve4;   // Note: for this property a default value is defined.
	sequenceFlow4.caseValues.push(noCase4);

	var voidType1 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var aCT_ShowRecipe1 = microflows.Microflow.createIn(unit);
	aCT_ShowRecipe1.name = "ACT_ShowRecipe";
	aCT_ShowRecipe1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	aCT_ShowRecipe1.flows.push(sequenceFlow1);
	aCT_ShowRecipe1.flows.push(sequenceFlow2);
	aCT_ShowRecipe1.flows.push(sequenceFlow3);
	aCT_ShowRecipe1.flows.push(sequenceFlow4);
	aCT_ShowRecipe1.microflowReturnType = voidType1;
	aCT_ShowRecipe1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	aCT_ShowRecipe1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = actionActivity2;

	sequenceFlow3.origin = actionActivity2;
	sequenceFlow3.destination = actionActivity3;

	sequenceFlow4.origin = actionActivity3;
	sequenceFlow4.destination = endEvent1;

})