(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "9a5a7857-f32d-444b-9500-14677f713462" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.HomeContext");

	var homeContext1 = microflows.MicroflowParameterObject.create(model);
	homeContext1.relativeMiddlePoint = {"x":60,"y":0};
	homeContext1.size = {"width":30,"height":30};
	homeContext1.name = "HomeContext";
	homeContext1.variableType = objectType1;   // Note: for this property a default value is defined.

	var memberChange1 = microflows.MemberChange.create(model);
	memberChange1.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Author");
	memberChange1.value = "'Unknown'";

	var memberChange2 = microflows.MemberChange.create(model);
	memberChange2.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedAt");
	memberChange2.value = "[%CurrentDateTime%]";

	var memberChange3 = microflows.MemberChange.create(model);
	memberChange3.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedTo");
	memberChange3.value = "'Mendix app'";

	var memberChange4 = microflows.MemberChange.create(model);
	memberChange4.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PreparationTimeInMinutes");
	memberChange4.value = "30";

	var createObjectAction1 = microflows.CreateObjectAction.create(model);
	createObjectAction1.items.push(memberChange1);
	createObjectAction1.items.push(memberChange2);
	createObjectAction1.items.push(memberChange3);
	createObjectAction1.items.push(memberChange4);
	createObjectAction1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");
	createObjectAction1.outputVariableName = "NewRecipe";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":200,"height":60};
	actionActivity1.action = createObjectAction1;

	var createObjectAction2 = microflows.CreateObjectAction.create(model);
	createObjectAction2.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeStep");
	createObjectAction2.outputVariableName = "NewRecipeStep";

	var actionActivity2 = microflows.ActionActivity.create(model);
	actionActivity2.relativeMiddlePoint = {"x":500,"y":120};
	actionActivity2.size = {"width":200,"height":60};
	actionActivity2.action = createObjectAction2;

	var memberChange5 = microflows.MemberChange.create(model);
	memberChange5.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Quantity");
	memberChange5.value = "1";

	var memberChange6 = microflows.MemberChange.create(model);
	memberChange6.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Unit");
	memberChange6.value = "'PIECE'";

	var createObjectAction3 = microflows.CreateObjectAction.create(model);
	createObjectAction3.items.push(memberChange5);
	createObjectAction3.items.push(memberChange6);
	createObjectAction3.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeIngredient");
	createObjectAction3.outputVariableName = "NewRecipeIngredient";

	var actionActivity3 = microflows.ActionActivity.create(model);
	actionActivity3.relativeMiddlePoint = {"x":720,"y":120};
	actionActivity3.size = {"width":200,"height":60};
	actionActivity3.action = createObjectAction3;

	var createObjectAction4 = microflows.CreateObjectAction.create(model);
	createObjectAction4.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeCategory");
	createObjectAction4.outputVariableName = "NewRecipeCategory";

	var actionActivity4 = microflows.ActionActivity.create(model);
	actionActivity4.relativeMiddlePoint = {"x":940,"y":120};
	actionActivity4.size = {"width":200,"height":60};
	actionActivity4.action = createObjectAction4;

	var memberChange7 = microflows.MemberChange.create(model);
	memberChange7.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeStep");
	memberChange7.type = microflows.ChangeActionItemType.Add;
	memberChange7.value = "$NewRecipeStep";

	var memberChange8 = microflows.MemberChange.create(model);
	memberChange8.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeIngredient");
	memberChange8.type = microflows.ChangeActionItemType.Add;
	memberChange8.value = "$NewRecipeIngredient";

	var memberChange9 = microflows.MemberChange.create(model);
	memberChange9.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeCategory");
	memberChange9.type = microflows.ChangeActionItemType.Add;
	memberChange9.value = "$NewRecipeCategory";

	var changeObjectAction1 = microflows.ChangeObjectAction.create(model);
	changeObjectAction1.items.push(memberChange7);
	changeObjectAction1.items.push(memberChange8);
	changeObjectAction1.items.push(memberChange9);
	changeObjectAction1.changeVariableName = "NewRecipe";

	var actionActivity5 = microflows.ActionActivity.create(model);
	actionActivity5.relativeMiddlePoint = {"x":1160,"y":120};
	actionActivity5.size = {"width":200,"height":60};
	actionActivity5.action = changeObjectAction1;

	var pageVariable1 = pages.PageVariable.create(model);

	var pageParameterMapping1 = pages.PageParameterMapping.create(model);
	pageParameterMapping1.parameter = model.findPageParameterByQualifiedName("MyFirstModule.Recipe_New.NewRecipe");
	pageParameterMapping1.variable = pageVariable1;
	pageParameterMapping1.argument = "$NewRecipe";

	var pageVariable2 = pages.PageVariable.create(model);

	var pageParameterMapping2 = pages.PageParameterMapping.create(model);
	pageParameterMapping2.parameter = model.findPageParameterByQualifiedName("MyFirstModule.Recipe_New.HomeContext");
	pageParameterMapping2.variable = pageVariable2;
	pageParameterMapping2.argument = "$HomeContext";

	var pageSettings1 = pages.PageSettings.create(model);
	pageSettings1.page = model.findPageByQualifiedName("MyFirstModule.Recipe_New");
	pageSettings1.parameterMappings.push(pageParameterMapping1);
	pageSettings1.parameterMappings.push(pageParameterMapping2);

	var showPageAction1 = microflows.ShowPageAction.create(model);
	showPageAction1.pageSettings = pageSettings1;   // Note: for this property a default value is defined.

	var actionActivity6 = microflows.ActionActivity.create(model);
	actionActivity6.relativeMiddlePoint = {"x":1380,"y":120};
	actionActivity6.size = {"width":210,"height":60};
	actionActivity6.action = showPageAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":1600,"y":120};
	endEvent1.size = {"width":20,"height":20};

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(homeContext1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(actionActivity2);
	microflowObjectCollection1.objects.push(actionActivity3);
	microflowObjectCollection1.objects.push(actionActivity4);
	microflowObjectCollection1.objects.push(actionActivity5);
	microflowObjectCollection1.objects.push(actionActivity6);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var bezierCurve3 = microflows.BezierCurve.create(model);
	bezierCurve3.originControlVector = {"width":30,"height":0};
	bezierCurve3.destinationControlVector = {"width":-30,"height":0};

	var noCase3 = microflows.NoCase.create(model);

	var sequenceFlow3 = microflows.SequenceFlow.create(model);
	sequenceFlow3.originConnectionIndex = 1;
	sequenceFlow3.destinationConnectionIndex = 3;
	sequenceFlow3.line = bezierCurve3;   // Note: for this property a default value is defined.
	sequenceFlow3.caseValues.push(noCase3);

	var bezierCurve4 = microflows.BezierCurve.create(model);
	bezierCurve4.originControlVector = {"width":30,"height":0};
	bezierCurve4.destinationControlVector = {"width":-30,"height":0};

	var noCase4 = microflows.NoCase.create(model);

	var sequenceFlow4 = microflows.SequenceFlow.create(model);
	sequenceFlow4.originConnectionIndex = 1;
	sequenceFlow4.destinationConnectionIndex = 3;
	sequenceFlow4.line = bezierCurve4;   // Note: for this property a default value is defined.
	sequenceFlow4.caseValues.push(noCase4);

	var bezierCurve5 = microflows.BezierCurve.create(model);
	bezierCurve5.originControlVector = {"width":30,"height":0};
	bezierCurve5.destinationControlVector = {"width":-30,"height":0};

	var noCase5 = microflows.NoCase.create(model);

	var sequenceFlow5 = microflows.SequenceFlow.create(model);
	sequenceFlow5.originConnectionIndex = 1;
	sequenceFlow5.destinationConnectionIndex = 3;
	sequenceFlow5.line = bezierCurve5;   // Note: for this property a default value is defined.
	sequenceFlow5.caseValues.push(noCase5);

	var bezierCurve6 = microflows.BezierCurve.create(model);
	bezierCurve6.originControlVector = {"width":30,"height":0};
	bezierCurve6.destinationControlVector = {"width":-30,"height":0};

	var noCase6 = microflows.NoCase.create(model);

	var sequenceFlow6 = microflows.SequenceFlow.create(model);
	sequenceFlow6.originConnectionIndex = 1;
	sequenceFlow6.destinationConnectionIndex = 3;
	sequenceFlow6.line = bezierCurve6;   // Note: for this property a default value is defined.
	sequenceFlow6.caseValues.push(noCase6);

	var bezierCurve7 = microflows.BezierCurve.create(model);
	bezierCurve7.originControlVector = {"width":30,"height":0};
	bezierCurve7.destinationControlVector = {"width":-30,"height":0};

	var noCase7 = microflows.NoCase.create(model);

	var sequenceFlow7 = microflows.SequenceFlow.create(model);
	sequenceFlow7.originConnectionIndex = 1;
	sequenceFlow7.destinationConnectionIndex = 3;
	sequenceFlow7.line = bezierCurve7;   // Note: for this property a default value is defined.
	sequenceFlow7.caseValues.push(noCase7);

	var voidType1 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var aCT_NewRecipe1 = microflows.Microflow.createIn(unit);
	aCT_NewRecipe1.name = "ACT_NewRecipe";
	aCT_NewRecipe1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	aCT_NewRecipe1.flows.push(sequenceFlow1);
	aCT_NewRecipe1.flows.push(sequenceFlow2);
	aCT_NewRecipe1.flows.push(sequenceFlow3);
	aCT_NewRecipe1.flows.push(sequenceFlow4);
	aCT_NewRecipe1.flows.push(sequenceFlow5);
	aCT_NewRecipe1.flows.push(sequenceFlow6);
	aCT_NewRecipe1.flows.push(sequenceFlow7);
	aCT_NewRecipe1.microflowReturnType = voidType1;
	aCT_NewRecipe1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	aCT_NewRecipe1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = actionActivity2;

	sequenceFlow3.origin = actionActivity2;
	sequenceFlow3.destination = actionActivity3;

	sequenceFlow4.origin = actionActivity3;
	sequenceFlow4.destination = actionActivity4;

	sequenceFlow5.origin = actionActivity4;
	sequenceFlow5.destination = actionActivity5;

	sequenceFlow6.origin = actionActivity5;
	sequenceFlow6.destination = actionActivity6;

	sequenceFlow7.origin = actionActivity6;
	sequenceFlow7.destination = endEvent1;

})