(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "9f860d40-4ee8-4876-94b2-232bef8f9495" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");

	var newRecipe1 = microflows.MicroflowParameterObject.create(model);
	newRecipe1.relativeMiddlePoint = {"x":60,"y":0};
	newRecipe1.size = {"width":30,"height":30};
	newRecipe1.name = "NewRecipe";
	newRecipe1.variableType = objectType1;   // Note: for this property a default value is defined.

	var objectType2 = datatypes.ObjectType.create(model);
	objectType2.entity = model.findEntityByQualifiedName("MyFirstModule.HomeContext");

	var homeContext1 = microflows.MicroflowParameterObject.create(model);
	homeContext1.relativeMiddlePoint = {"x":220,"y":0};
	homeContext1.size = {"width":30,"height":30};
	homeContext1.name = "HomeContext";
	homeContext1.variableType = objectType2;   // Note: for this property a default value is defined.

	var stringType1 = datatypes.StringType.create(model);

	var createVariableAction1 = microflows.CreateVariableAction.create(model);
	createVariableAction1.variableName = "Url";
	createVariableAction1.variableType = stringType1;   // Note: for this property a default value is defined.
	createVariableAction1.initialValue = "@MyFirstModule.RecipesApiBaseUrl + '/v1/recipes'";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":190,"height":60};
	actionActivity1.action = createVariableAction1;

	var templateArgument1 = microflows.TemplateArgument.create(model);
	templateArgument1.expression = "$Url";

	var stringTemplate1 = microflows.StringTemplate.create(model);
	stringTemplate1.arguments.push(templateArgument1);
	stringTemplate1.text = "{1}";

	var httpHeaderEntry1 = microflows.HttpHeaderEntry.create(model);
	httpHeaderEntry1.key = "Content-Type";
	httpHeaderEntry1.value = "'application/json'";

	var httpConfiguration1 = microflows.HttpConfiguration.create(model);
	httpConfiguration1.overrideLocation = true;
	httpConfiguration1.customLocationTemplate = stringTemplate1;
	httpConfiguration1.headerEntries.push(httpHeaderEntry1);

	var mappingRequestHandling1 = microflows.MappingRequestHandling.create(model);
	mappingRequestHandling1.mapping = model.findExportMappingByQualifiedName("MyFirstModule.CreateRecipe_ExportMapping");
	mappingRequestHandling1.mappingArgumentVariableName = "NewRecipe";

	var voidType1 = datatypes.VoidType.create(model);

	var resultHandling1 = microflows.ResultHandling.create(model);
	resultHandling1.variableType = voidType1;   // Note: for this property a default value is defined.

	var restCallAction1 = microflows.RestCallAction.create(model);
	restCallAction1.httpConfiguration = httpConfiguration1;   // Note: for this property a default value is defined.
	restCallAction1.requestHandling = mappingRequestHandling1;   // Note: for this property a default value is defined.
	restCallAction1.requestHandlingType = microflows.RequestHandlingType.Mapping;
	restCallAction1.resultHandling = resultHandling1;   // Note: for this property a default value is defined.

	var actionActivity2 = microflows.ActionActivity.create(model);
	actionActivity2.relativeMiddlePoint = {"x":500,"y":120};
	actionActivity2.size = {"width":190,"height":60};
	actionActivity2.action = restCallAction1;

	var changeObjectAction1 = microflows.ChangeObjectAction.create(model);
	changeObjectAction1.refreshInClient = true;
	changeObjectAction1.changeVariableName = "HomeContext";

	var actionActivity3 = microflows.ActionActivity.create(model);
	actionActivity3.relativeMiddlePoint = {"x":720,"y":120};
	actionActivity3.size = {"width":200,"height":60};
	actionActivity3.action = changeObjectAction1;

	var closeFormAction1 = microflows.CloseFormAction.create(model);

	var actionActivity4 = microflows.ActionActivity.create(model);
	actionActivity4.relativeMiddlePoint = {"x":940,"y":120};
	actionActivity4.size = {"width":160,"height":60};
	actionActivity4.action = closeFormAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":1160,"y":120};
	endEvent1.size = {"width":20,"height":20};

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(newRecipe1);
	microflowObjectCollection1.objects.push(homeContext1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(actionActivity2);
	microflowObjectCollection1.objects.push(actionActivity3);
	microflowObjectCollection1.objects.push(actionActivity4);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var bezierCurve3 = microflows.BezierCurve.create(model);
	bezierCurve3.originControlVector = {"width":30,"height":0};
	bezierCurve3.destinationControlVector = {"width":-30,"height":0};

	var noCase3 = microflows.NoCase.create(model);

	var sequenceFlow3 = microflows.SequenceFlow.create(model);
	sequenceFlow3.originConnectionIndex = 1;
	sequenceFlow3.destinationConnectionIndex = 3;
	sequenceFlow3.line = bezierCurve3;   // Note: for this property a default value is defined.
	sequenceFlow3.caseValues.push(noCase3);

	var bezierCurve4 = microflows.BezierCurve.create(model);
	bezierCurve4.originControlVector = {"width":30,"height":0};
	bezierCurve4.destinationControlVector = {"width":-30,"height":0};

	var noCase4 = microflows.NoCase.create(model);

	var sequenceFlow4 = microflows.SequenceFlow.create(model);
	sequenceFlow4.originConnectionIndex = 1;
	sequenceFlow4.destinationConnectionIndex = 3;
	sequenceFlow4.line = bezierCurve4;   // Note: for this property a default value is defined.
	sequenceFlow4.caseValues.push(noCase4);

	var bezierCurve5 = microflows.BezierCurve.create(model);
	bezierCurve5.originControlVector = {"width":30,"height":0};
	bezierCurve5.destinationControlVector = {"width":-30,"height":0};

	var noCase5 = microflows.NoCase.create(model);

	var sequenceFlow5 = microflows.SequenceFlow.create(model);
	sequenceFlow5.originConnectionIndex = 1;
	sequenceFlow5.destinationConnectionIndex = 3;
	sequenceFlow5.line = bezierCurve5;   // Note: for this property a default value is defined.
	sequenceFlow5.caseValues.push(noCase5);

	var voidType2 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var aCT_SaveRecipe1 = microflows.Microflow.createIn(unit);
	aCT_SaveRecipe1.name = "ACT_SaveRecipe";
	aCT_SaveRecipe1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	aCT_SaveRecipe1.flows.push(sequenceFlow1);
	aCT_SaveRecipe1.flows.push(sequenceFlow2);
	aCT_SaveRecipe1.flows.push(sequenceFlow3);
	aCT_SaveRecipe1.flows.push(sequenceFlow4);
	aCT_SaveRecipe1.flows.push(sequenceFlow5);
	aCT_SaveRecipe1.microflowReturnType = voidType2;
	aCT_SaveRecipe1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	aCT_SaveRecipe1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = actionActivity2;

	sequenceFlow3.origin = actionActivity2;
	sequenceFlow3.destination = actionActivity3;

	sequenceFlow4.origin = actionActivity3;
	sequenceFlow4.destination = actionActivity4;

	sequenceFlow5.origin = actionActivity4;
	sequenceFlow5.destination = endEvent1;

})