(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "0f54f197-e042-421b-b9f4-426b66fd490d" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeDetail");

	var recipeDetail1 = microflows.MicroflowParameterObject.create(model);
	recipeDetail1.relativeMiddlePoint = {"x":60,"y":0};
	recipeDetail1.size = {"width":30,"height":30};
	recipeDetail1.name = "RecipeDetail";
	recipeDetail1.variableType = objectType1;   // Note: for this property a default value is defined.

	var associationRetrieveSource1 = microflows.AssociationRetrieveSource.create(model);
	associationRetrieveSource1.startVariableName = "RecipeDetail";
	associationRetrieveSource1.association = model.findAssociationBaseByQualifiedName("MyFirstModule.RecipeCategory_RecipeDetail");

	var retrieveAction1 = microflows.RetrieveAction.create(model);
	retrieveAction1.retrieveSource = associationRetrieveSource1;   // Note: for this property a default value is defined.
	retrieveAction1.outputVariableName = "RecipeCategories";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":190,"height":60};
	actionActivity1.action = retrieveAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":500,"y":120};
	endEvent1.size = {"width":20,"height":20};
	endEvent1.returnValue = "$RecipeCategories";

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(recipeDetail1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var listType1 = datatypes.ListType.create(model);
	listType1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeCategory");

	var text1 = texts.Text.create(model);

	var dS_RecipeCategories1 = microflows.Microflow.createIn(unit);
	dS_RecipeCategories1.name = "DS_RecipeCategories";
	dS_RecipeCategories1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	dS_RecipeCategories1.flows.push(sequenceFlow1);
	dS_RecipeCategories1.flows.push(sequenceFlow2);
	dS_RecipeCategories1.microflowReturnType = listType1;
	dS_RecipeCategories1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	dS_RecipeCategories1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = endEvent1;

})