(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "74c7d594-9dc2-4277-ba59-5a0ccc1a2867" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":60,"y":120};
	startEvent1.size = {"width":20,"height":20};

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipeIngredient");

	var newRecipeIngredient1 = microflows.MicroflowParameterObject.create(model);
	newRecipeIngredient1.relativeMiddlePoint = {"x":60,"y":0};
	newRecipeIngredient1.size = {"width":30,"height":30};
	newRecipeIngredient1.name = "NewRecipeIngredient";
	newRecipeIngredient1.variableType = objectType1;   // Note: for this property a default value is defined.

	var objectType2 = datatypes.ObjectType.create(model);
	objectType2.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");

	var newRecipe1 = microflows.MicroflowParameterObject.create(model);
	newRecipe1.relativeMiddlePoint = {"x":220,"y":0};
	newRecipe1.size = {"width":30,"height":30};
	newRecipe1.name = "NewRecipe";
	newRecipe1.variableType = objectType2;   // Note: for this property a default value is defined.

	var memberChange1 = microflows.MemberChange.create(model);
	memberChange1.association = model.findAssociationBaseByQualifiedName("MyFirstModule.NewRecipe_NewRecipeIngredient");
	memberChange1.type = microflows.ChangeActionItemType.Remove;
	memberChange1.value = "$NewRecipeIngredient";

	var changeObjectAction1 = microflows.ChangeObjectAction.create(model);
	changeObjectAction1.items.push(memberChange1);
	changeObjectAction1.refreshInClient = true;
	changeObjectAction1.changeVariableName = "NewRecipe";

	var actionActivity1 = microflows.ActionActivity.create(model);
	actionActivity1.relativeMiddlePoint = {"x":280,"y":120};
	actionActivity1.size = {"width":200,"height":60};
	actionActivity1.action = changeObjectAction1;

	var deleteAction1 = microflows.DeleteAction.create(model);
	deleteAction1.deleteVariableName = "NewRecipeIngredient";

	var actionActivity2 = microflows.ActionActivity.create(model);
	actionActivity2.relativeMiddlePoint = {"x":500,"y":120};
	actionActivity2.size = {"width":190,"height":60};
	actionActivity2.action = deleteAction1;

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":720,"y":120};
	endEvent1.size = {"width":20,"height":20};

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(newRecipeIngredient1);
	microflowObjectCollection1.objects.push(newRecipe1);
	microflowObjectCollection1.objects.push(actionActivity1);
	microflowObjectCollection1.objects.push(actionActivity2);
	microflowObjectCollection1.objects.push(endEvent1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":30,"height":0};
	bezierCurve1.destinationControlVector = {"width":-30,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var bezierCurve2 = microflows.BezierCurve.create(model);
	bezierCurve2.originControlVector = {"width":30,"height":0};
	bezierCurve2.destinationControlVector = {"width":-30,"height":0};

	var noCase2 = microflows.NoCase.create(model);

	var sequenceFlow2 = microflows.SequenceFlow.create(model);
	sequenceFlow2.originConnectionIndex = 1;
	sequenceFlow2.destinationConnectionIndex = 3;
	sequenceFlow2.line = bezierCurve2;   // Note: for this property a default value is defined.
	sequenceFlow2.caseValues.push(noCase2);

	var bezierCurve3 = microflows.BezierCurve.create(model);
	bezierCurve3.originControlVector = {"width":30,"height":0};
	bezierCurve3.destinationControlVector = {"width":-30,"height":0};

	var noCase3 = microflows.NoCase.create(model);

	var sequenceFlow3 = microflows.SequenceFlow.create(model);
	sequenceFlow3.originConnectionIndex = 1;
	sequenceFlow3.destinationConnectionIndex = 3;
	sequenceFlow3.line = bezierCurve3;   // Note: for this property a default value is defined.
	sequenceFlow3.caseValues.push(noCase3);

	var voidType1 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var aCT_RemoveIngredient1 = microflows.Microflow.createIn(unit);
	aCT_RemoveIngredient1.name = "ACT_RemoveIngredient";
	aCT_RemoveIngredient1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	aCT_RemoveIngredient1.flows.push(sequenceFlow1);
	aCT_RemoveIngredient1.flows.push(sequenceFlow2);
	aCT_RemoveIngredient1.flows.push(sequenceFlow3);
	aCT_RemoveIngredient1.microflowReturnType = voidType1;
	aCT_RemoveIngredient1.allowedModuleRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	aCT_RemoveIngredient1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = actionActivity1;

	sequenceFlow2.origin = actionActivity1;
	sequenceFlow2.destination = actionActivity2;

	sequenceFlow3.origin = actionActivity2;
	sequenceFlow3.destination = endEvent1;

})