(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "4a8475b3-14cb-4100-8963-58f2fd3a0be8" of type Microflows$Microflow
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var startEvent1 = microflows.StartEvent.create(model);
	startEvent1.relativeMiddlePoint = {"x":-88,"y":199};
	startEvent1.size = {"width":20,"height":20};

	var endEvent1 = microflows.EndEvent.create(model);
	endEvent1.relativeMiddlePoint = {"x":217,"y":199};
	endEvent1.size = {"width":20,"height":20};

	var annotation1 = microflows.Annotation.create(model);
	annotation1.relativeMiddlePoint = {"x":97,"y":35};
	annotation1.size = {"width":385,"height":109};
	annotation1.caption = "Microflows are used to define server logic in your app.\r\n\r\n- For client logic you can use Nanoflows\r\n- For business process logic you can use Workflows\r\n\r\nDocumentation: https://docs.mendix.com/refguide/application-logic";

	var microflowObjectCollection1 = microflows.MicroflowObjectCollection.create(model);
	microflowObjectCollection1.objects.push(startEvent1);
	microflowObjectCollection1.objects.push(endEvent1);
	microflowObjectCollection1.objects.push(annotation1);

	var bezierCurve1 = microflows.BezierCurve.create(model);
	bezierCurve1.originControlVector = {"width":0,"height":0};
	bezierCurve1.destinationControlVector = {"width":-15,"height":0};

	var noCase1 = microflows.NoCase.create(model);

	var sequenceFlow1 = microflows.SequenceFlow.create(model);
	sequenceFlow1.originConnectionIndex = 1;
	sequenceFlow1.destinationConnectionIndex = 3;
	sequenceFlow1.line = bezierCurve1;   // Note: for this property a default value is defined.
	sequenceFlow1.caseValues.push(noCase1);

	var voidType1 = datatypes.VoidType.create(model);

	var text1 = texts.Text.create(model);

	var myFirstLogic1 = microflows.Microflow.createIn(unit);
	myFirstLogic1.name = "MyFirstLogic";
	myFirstLogic1.objectCollection = microflowObjectCollection1;   // Note: for this property a default value is defined.
	myFirstLogic1.flows.push(sequenceFlow1);
	myFirstLogic1.microflowReturnType = voidType1;
	myFirstLogic1.concurrencyErrorMessage = text1;   // Note: for this property a default value is defined.

	sequenceFlow1.origin = startEvent1;
	sequenceFlow1.destination = endEvent1;

})