(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "e1d588da-b733-457a-b551-661480e621d2" of type Pages$Page
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeDetail");

	var recipeDetail1 = pages.PageParameter.create(model);
	recipeDetail1.name = "RecipeDetail";
	recipeDetail1.parameterType = objectType1;   // Note: for this property a default value is defined.

	var appearance1 = pages.Appearance.create(model);
	appearance1.class = "recipe-detail";

	var directEntityRef1 = domainmodels.DirectEntityRef.create(model);
	directEntityRef1.entity = model.findEntityByQualifiedName("MyFirstModule.RecipeDetail");

	var pageVariable1 = pages.PageVariable.create(model);

	var dataViewSource1 = pages.DataViewSource.create(model);
	dataViewSource1.entityRef = directEntityRef1;
	dataViewSource1.sourceVariable = pageVariable1;

	var appearance2 = pages.Appearance.create(model);

	var appearance3 = pages.Appearance.create(model);

	var translation1 = texts.Translation.create(model);
	translation1.languageCode = "en_US";
	translation1.text = "Back";

	var text1 = texts.Text.create(model);
	text1.translations.push(translation1);

	var text2 = texts.Text.create(model);

	var clientTemplate1 = pages.ClientTemplate.create(model);
	clientTemplate1.template = text1;   // Note: for this property a default value is defined.
	clientTemplate1.fallback = text2;   // Note: for this property a default value is defined.

	var text3 = texts.Text.create(model);

	var closePageClientAction1 = pages.ClosePageClientAction.create(model);

	var backButton1 = pages.ActionButton.create(model);
	backButton1.name = "backButton";
	backButton1.appearance = appearance3;   // Note: for this property a default value is defined.
	backButton1.caption = clientTemplate1;   // Note: for this property a default value is defined.
	backButton1.tooltip = text3;   // Note: for this property a default value is defined.
	backButton1.renderType = pages.RenderType.Link;
	backButton1.action = closePageClientAction1;   // Note: for this property a default value is defined.

	var appearance4 = pages.Appearance.create(model);

	var layoutGridColumn1 = pages.LayoutGridColumn.create(model);
	layoutGridColumn1.weight = -1;
	layoutGridColumn1.widgets.push(backButton1);
	layoutGridColumn1.appearance = appearance4;   // Note: for this property a default value is defined.

	var appearance5 = pages.Appearance.create(model);

	var layoutGridRow1 = pages.LayoutGridRow.create(model);
	layoutGridRow1.columns.push(layoutGridColumn1);
	layoutGridRow1.appearance = appearance5;   // Note: for this property a default value is defined.

	var appearance6 = pages.Appearance.create(model);

	var translation2 = texts.Translation.create(model);
	translation2.languageCode = "en_US";
	translation2.text = "{1}";

	var text4 = texts.Text.create(model);
	text4.translations.push(translation2);

	var attributeRef1 = domainmodels.AttributeRef.create(model);
	attributeRef1.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Name");

	var formattingInfo1 = pages.FormattingInfo.create(model);

	var clientTemplateParameter1 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter1.attributeRef = attributeRef1;
	clientTemplateParameter1.formattingInfo = formattingInfo1;   // Note: for this property a default value is defined.

	var text5 = texts.Text.create(model);

	var clientTemplate2 = pages.ClientTemplate.create(model);
	clientTemplate2.template = text4;   // Note: for this property a default value is defined.
	clientTemplate2.parameters.push(clientTemplateParameter1);
	clientTemplate2.fallback = text5;   // Note: for this property a default value is defined.

	var detailName1 = pages.DynamicText.create(model);
	detailName1.name = "detailName";
	detailName1.appearance = appearance6;   // Note: for this property a default value is defined.
	detailName1.content = clientTemplate2;   // Note: for this property a default value is defined.
	detailName1.renderMode = pages.TextRenderMode.H1;

	var appearance7 = pages.Appearance.create(model);

	var translation3 = texts.Translation.create(model);
	translation3.languageCode = "en_US";
	translation3.text = "{1}";

	var text6 = texts.Text.create(model);
	text6.translations.push(translation3);

	var attributeRef2 = domainmodels.AttributeRef.create(model);
	attributeRef2.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Description");

	var formattingInfo2 = pages.FormattingInfo.create(model);

	var clientTemplateParameter2 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter2.attributeRef = attributeRef2;
	clientTemplateParameter2.formattingInfo = formattingInfo2;   // Note: for this property a default value is defined.

	var text7 = texts.Text.create(model);

	var clientTemplate3 = pages.ClientTemplate.create(model);
	clientTemplate3.template = text6;   // Note: for this property a default value is defined.
	clientTemplate3.parameters.push(clientTemplateParameter2);
	clientTemplate3.fallback = text7;   // Note: for this property a default value is defined.

	var detailDescription1 = pages.DynamicText.create(model);
	detailDescription1.name = "detailDescription";
	detailDescription1.appearance = appearance7;   // Note: for this property a default value is defined.
	detailDescription1.content = clientTemplate3;   // Note: for this property a default value is defined.

	var appearance8 = pages.Appearance.create(model);

	var translation4 = texts.Translation.create(model);
	translation4.languageCode = "en_US";
	translation4.text = "Preparation time: {1} minutes";

	var text8 = texts.Text.create(model);
	text8.translations.push(translation4);

	var attributeRef3 = domainmodels.AttributeRef.create(model);
	attributeRef3.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PreparationTimeInMinutes");

	var formattingInfo3 = pages.FormattingInfo.create(model);

	var clientTemplateParameter3 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter3.attributeRef = attributeRef3;
	clientTemplateParameter3.formattingInfo = formattingInfo3;   // Note: for this property a default value is defined.

	var text9 = texts.Text.create(model);

	var clientTemplate4 = pages.ClientTemplate.create(model);
	clientTemplate4.template = text8;   // Note: for this property a default value is defined.
	clientTemplate4.parameters.push(clientTemplateParameter3);
	clientTemplate4.fallback = text9;   // Note: for this property a default value is defined.

	var detailPreparationTime1 = pages.DynamicText.create(model);
	detailPreparationTime1.name = "detailPreparationTime";
	detailPreparationTime1.appearance = appearance8;   // Note: for this property a default value is defined.
	detailPreparationTime1.content = clientTemplate4;   // Note: for this property a default value is defined.

	var appearance9 = pages.Appearance.create(model);

	var translation5 = texts.Translation.create(model);
	translation5.languageCode = "en_US";
	translation5.text = "By {1}, posted to {2}";

	var text10 = texts.Text.create(model);
	text10.translations.push(translation5);

	var attributeRef4 = domainmodels.AttributeRef.create(model);
	attributeRef4.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.Author");

	var formattingInfo4 = pages.FormattingInfo.create(model);

	var clientTemplateParameter4 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter4.attributeRef = attributeRef4;
	clientTemplateParameter4.formattingInfo = formattingInfo4;   // Note: for this property a default value is defined.

	var attributeRef5 = domainmodels.AttributeRef.create(model);
	attributeRef5.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PostedTo");

	var formattingInfo5 = pages.FormattingInfo.create(model);

	var clientTemplateParameter5 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter5.attributeRef = attributeRef5;
	clientTemplateParameter5.formattingInfo = formattingInfo5;   // Note: for this property a default value is defined.

	var text11 = texts.Text.create(model);

	var clientTemplate5 = pages.ClientTemplate.create(model);
	clientTemplate5.template = text10;   // Note: for this property a default value is defined.
	clientTemplate5.parameters.push(clientTemplateParameter4);
	clientTemplate5.parameters.push(clientTemplateParameter5);
	clientTemplate5.fallback = text11;   // Note: for this property a default value is defined.

	var detailAuthor1 = pages.DynamicText.create(model);
	detailAuthor1.name = "detailAuthor";
	detailAuthor1.appearance = appearance9;   // Note: for this property a default value is defined.
	detailAuthor1.content = clientTemplate5;   // Note: for this property a default value is defined.

	var appearance10 = pages.Appearance.create(model);

	var translation6 = texts.Translation.create(model);
	translation6.languageCode = "en_US";
	translation6.text = "Posted at {1}";

	var text12 = texts.Text.create(model);
	text12.translations.push(translation6);

	var attributeRef6 = domainmodels.AttributeRef.create(model);
	attributeRef6.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeDetail.PostedAt");

	var formattingInfo6 = pages.FormattingInfo.create(model);

	var clientTemplateParameter6 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter6.attributeRef = attributeRef6;
	clientTemplateParameter6.formattingInfo = formattingInfo6;   // Note: for this property a default value is defined.

	var text13 = texts.Text.create(model);

	var clientTemplate6 = pages.ClientTemplate.create(model);
	clientTemplate6.template = text12;   // Note: for this property a default value is defined.
	clientTemplate6.parameters.push(clientTemplateParameter6);
	clientTemplate6.fallback = text13;   // Note: for this property a default value is defined.

	var detailPostedAt1 = pages.DynamicText.create(model);
	detailPostedAt1.name = "detailPostedAt";
	detailPostedAt1.appearance = appearance10;   // Note: for this property a default value is defined.
	detailPostedAt1.content = clientTemplate6;   // Note: for this property a default value is defined.

	var appearance11 = pages.Appearance.create(model);

	var layoutGridColumn2 = pages.LayoutGridColumn.create(model);
	layoutGridColumn2.weight = -1;
	layoutGridColumn2.widgets.push(detailName1);
	layoutGridColumn2.widgets.push(detailDescription1);
	layoutGridColumn2.widgets.push(detailPreparationTime1);
	layoutGridColumn2.widgets.push(detailAuthor1);
	layoutGridColumn2.widgets.push(detailPostedAt1);
	layoutGridColumn2.appearance = appearance11;   // Note: for this property a default value is defined.

	var appearance12 = pages.Appearance.create(model);

	var layoutGridRow2 = pages.LayoutGridRow.create(model);
	layoutGridRow2.columns.push(layoutGridColumn2);
	layoutGridRow2.appearance = appearance12;   // Note: for this property a default value is defined.

	var appearance13 = pages.Appearance.create(model);
	appearance13.class = "recipes-panel";

	var appearance14 = pages.Appearance.create(model);

	var translation7 = texts.Translation.create(model);
	translation7.languageCode = "en_US";
	translation7.text = "Ingredients";

	var text14 = texts.Text.create(model);
	text14.translations.push(translation7);

	var text15 = texts.Text.create(model);

	var clientTemplate7 = pages.ClientTemplate.create(model);
	clientTemplate7.template = text14;   // Note: for this property a default value is defined.
	clientTemplate7.fallback = text15;   // Note: for this property a default value is defined.

	var ingredientsHeader1 = pages.DynamicText.create(model);
	ingredientsHeader1.name = "ingredientsHeader";
	ingredientsHeader1.appearance = appearance14;   // Note: for this property a default value is defined.
	ingredientsHeader1.content = clientTemplate7;   // Note: for this property a default value is defined.
	ingredientsHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance15 = pages.Appearance.create(model);
	appearance15.class = "recipe-detail-list";

	var pageVariable2 = pages.PageVariable.create(model);

	var microflowParameterMapping1 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping1.__parameter.updateWithRawValue("MyFirstModule.DS_RecipeIngredients.RecipeDetail");
	microflowParameterMapping1.variable = pageVariable2;

	var microflowSettings1 = pages.MicroflowSettings.create(model);
	microflowSettings1.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_RecipeIngredients");
	microflowSettings1.parameterMappings.push(microflowParameterMapping1);

	var microflowSource1 = pages.MicroflowSource.create(model);
	microflowSource1.microflowSettings = microflowSettings1;   // Note: for this property a default value is defined.

	var appearance16 = pages.Appearance.create(model);

	var translation8 = texts.Translation.create(model);
	translation8.languageCode = "en_US";
	translation8.text = "{1} {2} {3}";

	var text16 = texts.Text.create(model);
	text16.translations.push(translation8);

	var attributeRef7 = domainmodels.AttributeRef.create(model);
	attributeRef7.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Quantity");

	var formattingInfo7 = pages.FormattingInfo.create(model);

	var clientTemplateParameter7 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter7.attributeRef = attributeRef7;
	clientTemplateParameter7.formattingInfo = formattingInfo7;   // Note: for this property a default value is defined.

	var attributeRef8 = domainmodels.AttributeRef.create(model);
	attributeRef8.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Unit");

	var formattingInfo8 = pages.FormattingInfo.create(model);

	var clientTemplateParameter8 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter8.attributeRef = attributeRef8;
	clientTemplateParameter8.formattingInfo = formattingInfo8;   // Note: for this property a default value is defined.

	var attributeRef9 = domainmodels.AttributeRef.create(model);
	attributeRef9.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeIngredient.Name");

	var formattingInfo9 = pages.FormattingInfo.create(model);

	var clientTemplateParameter9 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter9.attributeRef = attributeRef9;
	clientTemplateParameter9.formattingInfo = formattingInfo9;   // Note: for this property a default value is defined.

	var text17 = texts.Text.create(model);

	var clientTemplate8 = pages.ClientTemplate.create(model);
	clientTemplate8.template = text16;   // Note: for this property a default value is defined.
	clientTemplate8.parameters.push(clientTemplateParameter7);
	clientTemplate8.parameters.push(clientTemplateParameter8);
	clientTemplate8.parameters.push(clientTemplateParameter9);
	clientTemplate8.fallback = text17;   // Note: for this property a default value is defined.

	var ingredient1 = pages.DynamicText.create(model);
	ingredient1.name = "ingredient";
	ingredient1.appearance = appearance16;   // Note: for this property a default value is defined.
	ingredient1.content = clientTemplate8;   // Note: for this property a default value is defined.

	var noClientAction1 = pages.NoClientAction.create(model);

	var noClientAction2 = pages.NoClientAction.create(model);

	var ingredientList1 = pages.ListView.create(model);
	ingredientList1.name = "ingredientList";
	ingredientList1.appearance = appearance15;   // Note: for this property a default value is defined.
	ingredientList1.dataSource = microflowSource1;
	ingredientList1.widgets.push(ingredient1);
	ingredientList1.clickAction = noClientAction1;   // Note: for this property a default value is defined.
	ingredientList1.pullDownAction = noClientAction2;   // Note: for this property a default value is defined.

	var noClientAction3 = pages.NoClientAction.create(model);

	var ingredientsPanel1 = pages.DivContainer.create(model);
	ingredientsPanel1.name = "ingredientsPanel";
	ingredientsPanel1.appearance = appearance13;   // Note: for this property a default value is defined.
	ingredientsPanel1.widgets.push(ingredientsHeader1);
	ingredientsPanel1.widgets.push(ingredientList1);
	ingredientsPanel1.onClickAction = noClientAction3;   // Note: for this property a default value is defined.

	var appearance17 = pages.Appearance.create(model);

	var layoutGridColumn3 = pages.LayoutGridColumn.create(model);
	layoutGridColumn3.weight = 5;
	layoutGridColumn3.widgets.push(ingredientsPanel1);
	layoutGridColumn3.appearance = appearance17;   // Note: for this property a default value is defined.

	var appearance18 = pages.Appearance.create(model);
	appearance18.class = "recipes-panel";

	var appearance19 = pages.Appearance.create(model);

	var translation9 = texts.Translation.create(model);
	translation9.languageCode = "en_US";
	translation9.text = "Steps";

	var text18 = texts.Text.create(model);
	text18.translations.push(translation9);

	var text19 = texts.Text.create(model);

	var clientTemplate9 = pages.ClientTemplate.create(model);
	clientTemplate9.template = text18;   // Note: for this property a default value is defined.
	clientTemplate9.fallback = text19;   // Note: for this property a default value is defined.

	var stepsHeader1 = pages.DynamicText.create(model);
	stepsHeader1.name = "stepsHeader";
	stepsHeader1.appearance = appearance19;   // Note: for this property a default value is defined.
	stepsHeader1.content = clientTemplate9;   // Note: for this property a default value is defined.
	stepsHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance20 = pages.Appearance.create(model);
	appearance20.class = "recipe-detail-list";

	var pageVariable3 = pages.PageVariable.create(model);

	var microflowParameterMapping2 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping2.__parameter.updateWithRawValue("MyFirstModule.DS_RecipeSteps.RecipeDetail");
	microflowParameterMapping2.variable = pageVariable3;

	var microflowSettings2 = pages.MicroflowSettings.create(model);
	microflowSettings2.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_RecipeSteps");
	microflowSettings2.parameterMappings.push(microflowParameterMapping2);

	var microflowSource2 = pages.MicroflowSource.create(model);
	microflowSource2.microflowSettings = microflowSettings2;   // Note: for this property a default value is defined.

	var appearance21 = pages.Appearance.create(model);

	var translation10 = texts.Translation.create(model);
	translation10.languageCode = "en_US";
	translation10.text = "{1}";

	var text20 = texts.Text.create(model);
	text20.translations.push(translation10);

	var attributeRef10 = domainmodels.AttributeRef.create(model);
	attributeRef10.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeStep.Description");

	var formattingInfo10 = pages.FormattingInfo.create(model);

	var clientTemplateParameter10 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter10.attributeRef = attributeRef10;
	clientTemplateParameter10.formattingInfo = formattingInfo10;   // Note: for this property a default value is defined.

	var text21 = texts.Text.create(model);

	var clientTemplate10 = pages.ClientTemplate.create(model);
	clientTemplate10.template = text20;   // Note: for this property a default value is defined.
	clientTemplate10.parameters.push(clientTemplateParameter10);
	clientTemplate10.fallback = text21;   // Note: for this property a default value is defined.

	var stepDescription1 = pages.DynamicText.create(model);
	stepDescription1.name = "stepDescription";
	stepDescription1.appearance = appearance21;   // Note: for this property a default value is defined.
	stepDescription1.content = clientTemplate10;   // Note: for this property a default value is defined.

	var noClientAction4 = pages.NoClientAction.create(model);

	var noClientAction5 = pages.NoClientAction.create(model);

	var stepList1 = pages.ListView.create(model);
	stepList1.name = "stepList";
	stepList1.appearance = appearance20;   // Note: for this property a default value is defined.
	stepList1.dataSource = microflowSource2;
	stepList1.widgets.push(stepDescription1);
	stepList1.clickAction = noClientAction4;   // Note: for this property a default value is defined.
	stepList1.pullDownAction = noClientAction5;   // Note: for this property a default value is defined.

	var noClientAction6 = pages.NoClientAction.create(model);

	var stepsPanel1 = pages.DivContainer.create(model);
	stepsPanel1.name = "stepsPanel";
	stepsPanel1.appearance = appearance18;   // Note: for this property a default value is defined.
	stepsPanel1.widgets.push(stepsHeader1);
	stepsPanel1.widgets.push(stepList1);
	stepsPanel1.onClickAction = noClientAction6;   // Note: for this property a default value is defined.

	var appearance22 = pages.Appearance.create(model);

	var layoutGridColumn4 = pages.LayoutGridColumn.create(model);
	layoutGridColumn4.weight = 7;
	layoutGridColumn4.widgets.push(stepsPanel1);
	layoutGridColumn4.appearance = appearance22;   // Note: for this property a default value is defined.

	var appearance23 = pages.Appearance.create(model);

	var layoutGridRow3 = pages.LayoutGridRow.create(model);
	layoutGridRow3.columns.push(layoutGridColumn3);
	layoutGridRow3.columns.push(layoutGridColumn4);
	layoutGridRow3.appearance = appearance23;   // Note: for this property a default value is defined.

	var appearance24 = pages.Appearance.create(model);
	appearance24.class = "recipes-panel";

	var appearance25 = pages.Appearance.create(model);

	var translation11 = texts.Translation.create(model);
	translation11.languageCode = "en_US";
	translation11.text = "Categories";

	var text22 = texts.Text.create(model);
	text22.translations.push(translation11);

	var text23 = texts.Text.create(model);

	var clientTemplate11 = pages.ClientTemplate.create(model);
	clientTemplate11.template = text22;   // Note: for this property a default value is defined.
	clientTemplate11.fallback = text23;   // Note: for this property a default value is defined.

	var recipeCategoriesHeader1 = pages.DynamicText.create(model);
	recipeCategoriesHeader1.name = "recipeCategoriesHeader";
	recipeCategoriesHeader1.appearance = appearance25;   // Note: for this property a default value is defined.
	recipeCategoriesHeader1.content = clientTemplate11;   // Note: for this property a default value is defined.
	recipeCategoriesHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance26 = pages.Appearance.create(model);
	appearance26.class = "recipe-detail-list";

	var pageVariable4 = pages.PageVariable.create(model);

	var microflowParameterMapping3 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping3.__parameter.updateWithRawValue("MyFirstModule.DS_RecipeCategories.RecipeDetail");
	microflowParameterMapping3.variable = pageVariable4;

	var microflowSettings3 = pages.MicroflowSettings.create(model);
	microflowSettings3.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_RecipeCategories");
	microflowSettings3.parameterMappings.push(microflowParameterMapping3);

	var microflowSource3 = pages.MicroflowSource.create(model);
	microflowSource3.microflowSettings = microflowSettings3;   // Note: for this property a default value is defined.

	var appearance27 = pages.Appearance.create(model);

	var translation12 = texts.Translation.create(model);
	translation12.languageCode = "en_US";
	translation12.text = "{1}";

	var text24 = texts.Text.create(model);
	text24.translations.push(translation12);

	var attributeRef11 = domainmodels.AttributeRef.create(model);
	attributeRef11.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeCategory.Name");

	var formattingInfo11 = pages.FormattingInfo.create(model);

	var clientTemplateParameter11 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter11.attributeRef = attributeRef11;
	clientTemplateParameter11.formattingInfo = formattingInfo11;   // Note: for this property a default value is defined.

	var text25 = texts.Text.create(model);

	var clientTemplate12 = pages.ClientTemplate.create(model);
	clientTemplate12.template = text24;   // Note: for this property a default value is defined.
	clientTemplate12.parameters.push(clientTemplateParameter11);
	clientTemplate12.fallback = text25;   // Note: for this property a default value is defined.

	var recipeCategoryName1 = pages.DynamicText.create(model);
	recipeCategoryName1.name = "recipeCategoryName";
	recipeCategoryName1.appearance = appearance27;   // Note: for this property a default value is defined.
	recipeCategoryName1.content = clientTemplate12;   // Note: for this property a default value is defined.

	var noClientAction7 = pages.NoClientAction.create(model);

	var noClientAction8 = pages.NoClientAction.create(model);

	var recipeCategoryList1 = pages.ListView.create(model);
	recipeCategoryList1.name = "recipeCategoryList";
	recipeCategoryList1.appearance = appearance26;   // Note: for this property a default value is defined.
	recipeCategoryList1.dataSource = microflowSource3;
	recipeCategoryList1.widgets.push(recipeCategoryName1);
	recipeCategoryList1.clickAction = noClientAction7;   // Note: for this property a default value is defined.
	recipeCategoryList1.pullDownAction = noClientAction8;   // Note: for this property a default value is defined.

	var noClientAction9 = pages.NoClientAction.create(model);

	var recipeCategoriesPanel1 = pages.DivContainer.create(model);
	recipeCategoriesPanel1.name = "recipeCategoriesPanel";
	recipeCategoriesPanel1.appearance = appearance24;   // Note: for this property a default value is defined.
	recipeCategoriesPanel1.widgets.push(recipeCategoriesHeader1);
	recipeCategoriesPanel1.widgets.push(recipeCategoryList1);
	recipeCategoriesPanel1.onClickAction = noClientAction9;   // Note: for this property a default value is defined.

	var appearance28 = pages.Appearance.create(model);

	var layoutGridColumn5 = pages.LayoutGridColumn.create(model);
	layoutGridColumn5.weight = -1;
	layoutGridColumn5.widgets.push(recipeCategoriesPanel1);
	layoutGridColumn5.appearance = appearance28;   // Note: for this property a default value is defined.

	var appearance29 = pages.Appearance.create(model);

	var layoutGridRow4 = pages.LayoutGridRow.create(model);
	layoutGridRow4.columns.push(layoutGridColumn5);
	layoutGridRow4.appearance = appearance29;   // Note: for this property a default value is defined.

	var layoutGrid1 = pages.LayoutGrid.create(model);
	layoutGrid1.appearance = appearance2;   // Note: for this property a default value is defined.
	layoutGrid1.rows.push(layoutGridRow1);
	layoutGrid1.rows.push(layoutGridRow2);
	layoutGrid1.rows.push(layoutGridRow3);
	layoutGrid1.rows.push(layoutGridRow4);

	var text26 = texts.Text.create(model);

	var recipeDataView1 = pages.DataView.create(model);
	recipeDataView1.name = "recipeDataView";
	recipeDataView1.appearance = appearance1;   // Note: for this property a default value is defined.
	recipeDataView1.dataSource = dataViewSource1;
	recipeDataView1.widgets.push(layoutGrid1);
	recipeDataView1.editability = pages.EditableEnum.Never;
	recipeDataView1.showFooter = false;
	recipeDataView1.noEntityMessage = text26;   // Note: for this property a default value is defined.

	var layoutCallArgument1 = pages.LayoutCallArgument.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	layoutCallArgument1.__parameter.updateWithRawValue("Atlas_Core.Atlas_TopBar.Main");
	layoutCallArgument1.widgets.push(recipeDataView1);

	var layoutCall1 = pages.LayoutCall.create(model);
	layoutCall1.layout = model.findLayoutByQualifiedName("Atlas_Core.Atlas_TopBar");
	layoutCall1.arguments.push(layoutCallArgument1);

	var translation13 = texts.Translation.create(model);
	translation13.languageCode = "en_US";
	translation13.text = "Recipe";

	var text27 = texts.Text.create(model);
	text27.translations.push(translation13);

	var appearance30 = pages.Appearance.create(model);

	var recipe_Detail1 = pages.Page.createIn(unit);
	recipe_Detail1.name = "Recipe_Detail";
	recipe_Detail1.canvasWidth = 1200;
	recipe_Detail1.parameters.push(recipeDetail1);
	recipe_Detail1.layoutCall = layoutCall1;   // Note: for this property a default value is defined.
	recipe_Detail1.title = text27;   // Note: for this property a default value is defined.
	recipe_Detail1.appearance = appearance30;   // Note: for this property a default value is defined.
	recipe_Detail1.allowedRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));

	pageVariable1.pageParameter = recipeDetail1;

	pageVariable2.widget = recipeDataView1;

	pageVariable3.widget = recipeDataView1;

	pageVariable4.widget = recipeDataView1;

})