(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "5c6805fc-cadf-4d72-a5ef-f25da7cf4c97" of type Pages$Page
	 * in working copy "mendix-recipes"
	 * on 11-9-2026.
	 */

	var appearance1 = pages.Appearance.create(model);
	appearance1.class = "recipes-home";

	var microflowSettings1 = pages.MicroflowSettings.create(model);
	microflowSettings1.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_HomeContext");

	var microflowSource1 = pages.MicroflowSource.create(model);
	microflowSource1.microflowSettings = microflowSettings1;   // Note: for this property a default value is defined.

	var appearance2 = pages.Appearance.create(model);

	var appearance3 = pages.Appearance.create(model);

	var translation1 = texts.Translation.create(model);
	translation1.languageCode = "en_US";
	translation1.text = "Recipes";

	var text1 = texts.Text.create(model);
	text1.translations.push(translation1);

	var text2 = texts.Text.create(model);

	var clientTemplate1 = pages.ClientTemplate.create(model);
	clientTemplate1.template = text1;   // Note: for this property a default value is defined.
	clientTemplate1.fallback = text2;   // Note: for this property a default value is defined.

	var pageHeader1 = pages.DynamicText.create(model);
	pageHeader1.name = "pageHeader";
	pageHeader1.appearance = appearance3;   // Note: for this property a default value is defined.
	pageHeader1.content = clientTemplate1;   // Note: for this property a default value is defined.
	pageHeader1.renderMode = pages.TextRenderMode.H1;

	var appearance4 = pages.Appearance.create(model);

	var layoutGridColumn1 = pages.LayoutGridColumn.create(model);
	layoutGridColumn1.weight = -1;
	layoutGridColumn1.widgets.push(pageHeader1);
	layoutGridColumn1.appearance = appearance4;   // Note: for this property a default value is defined.

	var appearance5 = pages.Appearance.create(model);

	var layoutGridRow1 = pages.LayoutGridRow.create(model);
	layoutGridRow1.columns.push(layoutGridColumn1);
	layoutGridRow1.appearance = appearance5;   // Note: for this property a default value is defined.

	var appearance6 = pages.Appearance.create(model);
	appearance6.class = "recipes-panel";

	var appearance7 = pages.Appearance.create(model);

	var translation2 = texts.Translation.create(model);
	translation2.languageCode = "en_US";
	translation2.text = "Categories";

	var text3 = texts.Text.create(model);
	text3.translations.push(translation2);

	var text4 = texts.Text.create(model);

	var clientTemplate2 = pages.ClientTemplate.create(model);
	clientTemplate2.template = text3;   // Note: for this property a default value is defined.
	clientTemplate2.fallback = text4;   // Note: for this property a default value is defined.

	var categoriesHeader1 = pages.DynamicText.create(model);
	categoriesHeader1.name = "categoriesHeader";
	categoriesHeader1.appearance = appearance7;   // Note: for this property a default value is defined.
	categoriesHeader1.content = clientTemplate2;   // Note: for this property a default value is defined.
	categoriesHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance8 = pages.Appearance.create(model);

	var translation3 = texts.Translation.create(model);
	translation3.languageCode = "en_US";
	translation3.text = "All recipes";

	var text5 = texts.Text.create(model);
	text5.translations.push(translation3);

	var text6 = texts.Text.create(model);

	var clientTemplate3 = pages.ClientTemplate.create(model);
	clientTemplate3.template = text5;   // Note: for this property a default value is defined.
	clientTemplate3.fallback = text6;   // Note: for this property a default value is defined.

	var text7 = texts.Text.create(model);

	var microflowSettings2 = pages.MicroflowSettings.create(model);
	microflowSettings2.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_ShowAllRecipes");

	var microflowClientAction1 = pages.MicroflowClientAction.create(model);
	microflowClientAction1.microflowSettings = microflowSettings2;   // Note: for this property a default value is defined.

	var showAllRecipesButton1 = pages.ActionButton.create(model);
	showAllRecipesButton1.name = "showAllRecipesButton";
	showAllRecipesButton1.appearance = appearance8;   // Note: for this property a default value is defined.
	showAllRecipesButton1.caption = clientTemplate3;   // Note: for this property a default value is defined.
	showAllRecipesButton1.tooltip = text7;   // Note: for this property a default value is defined.
	showAllRecipesButton1.renderType = pages.RenderType.Link;
	showAllRecipesButton1.action = microflowClientAction1;   // Note: for this property a default value is defined.

	var appearance9 = pages.Appearance.create(model);
	appearance9.class = "recipes-category-list";

	var microflowSettings3 = pages.MicroflowSettings.create(model);
	microflowSettings3.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_Categories");

	var microflowSource2 = pages.MicroflowSource.create(model);
	microflowSource2.microflowSettings = microflowSettings3;   // Note: for this property a default value is defined.

	var appearance10 = pages.Appearance.create(model);

	var translation4 = texts.Translation.create(model);
	translation4.languageCode = "en_US";
	translation4.text = "{1}";

	var text8 = texts.Text.create(model);
	text8.translations.push(translation4);

	var attributeRef1 = domainmodels.AttributeRef.create(model);
	attributeRef1.attribute = model.findAttributeByQualifiedName("MyFirstModule.Category.Name");

	var formattingInfo1 = pages.FormattingInfo.create(model);

	var clientTemplateParameter1 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter1.attributeRef = attributeRef1;
	clientTemplateParameter1.formattingInfo = formattingInfo1;   // Note: for this property a default value is defined.

	var text9 = texts.Text.create(model);

	var clientTemplate4 = pages.ClientTemplate.create(model);
	clientTemplate4.template = text8;   // Note: for this property a default value is defined.
	clientTemplate4.parameters.push(clientTemplateParameter1);
	clientTemplate4.fallback = text9;   // Note: for this property a default value is defined.

	var categoryName1 = pages.DynamicText.create(model);
	categoryName1.name = "categoryName";
	categoryName1.appearance = appearance10;   // Note: for this property a default value is defined.
	categoryName1.content = clientTemplate4;   // Note: for this property a default value is defined.

	var microflowSettings4 = pages.MicroflowSettings.create(model);
	microflowSettings4.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_SelectCategory");

	var microflowClientAction2 = pages.MicroflowClientAction.create(model);
	microflowClientAction2.microflowSettings = microflowSettings4;   // Note: for this property a default value is defined.

	var noClientAction1 = pages.NoClientAction.create(model);

	var categoryList1 = pages.ListView.create(model);
	categoryList1.name = "categoryList";
	categoryList1.appearance = appearance9;   // Note: for this property a default value is defined.
	categoryList1.dataSource = microflowSource2;
	categoryList1.widgets.push(categoryName1);
	categoryList1.clickAction = microflowClientAction2;   // Note: for this property a default value is defined.
	categoryList1.pullDownAction = noClientAction1;   // Note: for this property a default value is defined.

	var noClientAction2 = pages.NoClientAction.create(model);

	var categoriesPanel1 = pages.DivContainer.create(model);
	categoriesPanel1.name = "categoriesPanel";
	categoriesPanel1.appearance = appearance6;   // Note: for this property a default value is defined.
	categoriesPanel1.widgets.push(categoriesHeader1);
	categoriesPanel1.widgets.push(showAllRecipesButton1);
	categoriesPanel1.widgets.push(categoryList1);
	categoriesPanel1.onClickAction = noClientAction2;   // Note: for this property a default value is defined.

	var appearance11 = pages.Appearance.create(model);

	var layoutGridColumn2 = pages.LayoutGridColumn.create(model);
	layoutGridColumn2.weight = 3;
	layoutGridColumn2.widgets.push(categoriesPanel1);
	layoutGridColumn2.appearance = appearance11;   // Note: for this property a default value is defined.

	var appearance12 = pages.Appearance.create(model);
	appearance12.class = "recipes-panel";

	var appearance13 = pages.Appearance.create(model);

	var translation5 = texts.Translation.create(model);
	translation5.languageCode = "en_US";
	translation5.text = "Recipes";

	var text10 = texts.Text.create(model);
	text10.translations.push(translation5);

	var text11 = texts.Text.create(model);

	var clientTemplate5 = pages.ClientTemplate.create(model);
	clientTemplate5.template = text10;   // Note: for this property a default value is defined.
	clientTemplate5.fallback = text11;   // Note: for this property a default value is defined.

	var recipesHeader1 = pages.DynamicText.create(model);
	recipesHeader1.name = "recipesHeader";
	recipesHeader1.appearance = appearance13;   // Note: for this property a default value is defined.
	recipesHeader1.content = clientTemplate5;   // Note: for this property a default value is defined.
	recipesHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance14 = pages.Appearance.create(model);

	var translation6 = texts.Translation.create(model);
	translation6.languageCode = "en_US";
	translation6.text = "Add a recipe";

	var text12 = texts.Text.create(model);
	text12.translations.push(translation6);

	var text13 = texts.Text.create(model);

	var clientTemplate6 = pages.ClientTemplate.create(model);
	clientTemplate6.template = text12;   // Note: for this property a default value is defined.
	clientTemplate6.fallback = text13;   // Note: for this property a default value is defined.

	var text14 = texts.Text.create(model);

	var microflowSettings5 = pages.MicroflowSettings.create(model);
	microflowSettings5.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_NewRecipe");

	var microflowClientAction3 = pages.MicroflowClientAction.create(model);
	microflowClientAction3.microflowSettings = microflowSettings5;   // Note: for this property a default value is defined.

	var addRecipeButton1 = pages.ActionButton.create(model);
	addRecipeButton1.name = "addRecipeButton";
	addRecipeButton1.appearance = appearance14;   // Note: for this property a default value is defined.
	addRecipeButton1.caption = clientTemplate6;   // Note: for this property a default value is defined.
	addRecipeButton1.tooltip = text14;   // Note: for this property a default value is defined.
	addRecipeButton1.renderType = pages.RenderType.Link;
	addRecipeButton1.action = microflowClientAction3;   // Note: for this property a default value is defined.

	var appearance15 = pages.Appearance.create(model);

	var translation7 = texts.Translation.create(model);
	translation7.languageCode = "en_US";
	translation7.text = "Filtered by: {1}";

	var text15 = texts.Text.create(model);
	text15.translations.push(translation7);

	var attributeRef2 = domainmodels.AttributeRef.create(model);
	attributeRef2.attribute = model.findAttributeByQualifiedName("MyFirstModule.HomeContext.SelectedCategory");

	var formattingInfo2 = pages.FormattingInfo.create(model);

	var clientTemplateParameter2 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter2.attributeRef = attributeRef2;
	clientTemplateParameter2.formattingInfo = formattingInfo2;   // Note: for this property a default value is defined.

	var text16 = texts.Text.create(model);

	var clientTemplate7 = pages.ClientTemplate.create(model);
	clientTemplate7.template = text15;   // Note: for this property a default value is defined.
	clientTemplate7.parameters.push(clientTemplateParameter2);
	clientTemplate7.fallback = text16;   // Note: for this property a default value is defined.

	var selectedCategory1 = pages.DynamicText.create(model);
	selectedCategory1.name = "selectedCategory";
	selectedCategory1.appearance = appearance15;   // Note: for this property a default value is defined.
	selectedCategory1.content = clientTemplate7;   // Note: for this property a default value is defined.
	selectedCategory1.renderMode = pages.TextRenderMode.Paragraph;

	var appearance16 = pages.Appearance.create(model);
	appearance16.class = "recipes-recipe-list";

	var pageVariable1 = pages.PageVariable.create(model);

	var microflowParameterMapping1 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping1.__parameter.updateWithRawValue("MyFirstModule.DS_Recipes.HomeContext");
	microflowParameterMapping1.variable = pageVariable1;

	var microflowSettings6 = pages.MicroflowSettings.create(model);
	microflowSettings6.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_Recipes");
	microflowSettings6.parameterMappings.push(microflowParameterMapping1);

	var microflowSource3 = pages.MicroflowSource.create(model);
	microflowSource3.microflowSettings = microflowSettings6;   // Note: for this property a default value is defined.

	var appearance17 = pages.Appearance.create(model);

	var translation8 = texts.Translation.create(model);
	translation8.languageCode = "en_US";
	translation8.text = "{1}";

	var text17 = texts.Text.create(model);
	text17.translations.push(translation8);

	var attributeRef3 = domainmodels.AttributeRef.create(model);
	attributeRef3.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.Name");

	var formattingInfo3 = pages.FormattingInfo.create(model);

	var clientTemplateParameter3 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter3.attributeRef = attributeRef3;
	clientTemplateParameter3.formattingInfo = formattingInfo3;   // Note: for this property a default value is defined.

	var text18 = texts.Text.create(model);

	var clientTemplate8 = pages.ClientTemplate.create(model);
	clientTemplate8.template = text17;   // Note: for this property a default value is defined.
	clientTemplate8.parameters.push(clientTemplateParameter3);
	clientTemplate8.fallback = text18;   // Note: for this property a default value is defined.

	var recipeName1 = pages.DynamicText.create(model);
	recipeName1.name = "recipeName";
	recipeName1.appearance = appearance17;   // Note: for this property a default value is defined.
	recipeName1.content = clientTemplate8;   // Note: for this property a default value is defined.
	recipeName1.renderMode = pages.TextRenderMode.H3;

	var appearance18 = pages.Appearance.create(model);

	var translation9 = texts.Translation.create(model);
	translation9.languageCode = "en_US";
	translation9.text = "{1}";

	var text19 = texts.Text.create(model);
	text19.translations.push(translation9);

	var attributeRef4 = domainmodels.AttributeRef.create(model);
	attributeRef4.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.DescriptionPrefix");

	var formattingInfo4 = pages.FormattingInfo.create(model);

	var clientTemplateParameter4 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter4.attributeRef = attributeRef4;
	clientTemplateParameter4.formattingInfo = formattingInfo4;   // Note: for this property a default value is defined.

	var text20 = texts.Text.create(model);

	var clientTemplate9 = pages.ClientTemplate.create(model);
	clientTemplate9.template = text19;   // Note: for this property a default value is defined.
	clientTemplate9.parameters.push(clientTemplateParameter4);
	clientTemplate9.fallback = text20;   // Note: for this property a default value is defined.

	var recipeDescription1 = pages.DynamicText.create(model);
	recipeDescription1.name = "recipeDescription";
	recipeDescription1.appearance = appearance18;   // Note: for this property a default value is defined.
	recipeDescription1.content = clientTemplate9;   // Note: for this property a default value is defined.
	recipeDescription1.renderMode = pages.TextRenderMode.Paragraph;

	var appearance19 = pages.Appearance.create(model);

	var translation10 = texts.Translation.create(model);
	translation10.languageCode = "en_US";
	translation10.text = "Ready in {1} minutes";

	var text21 = texts.Text.create(model);
	text21.translations.push(translation10);

	var attributeRef5 = domainmodels.AttributeRef.create(model);
	attributeRef5.attribute = model.findAttributeByQualifiedName("MyFirstModule.RecipeSummary.PreparationTimeInMinutes");

	var formattingInfo5 = pages.FormattingInfo.create(model);

	var clientTemplateParameter5 = pages.ClientTemplateParameter.create(model);
	clientTemplateParameter5.attributeRef = attributeRef5;
	clientTemplateParameter5.formattingInfo = formattingInfo5;   // Note: for this property a default value is defined.

	var text22 = texts.Text.create(model);

	var clientTemplate10 = pages.ClientTemplate.create(model);
	clientTemplate10.template = text21;   // Note: for this property a default value is defined.
	clientTemplate10.parameters.push(clientTemplateParameter5);
	clientTemplate10.fallback = text22;   // Note: for this property a default value is defined.

	var recipePreparationTime1 = pages.DynamicText.create(model);
	recipePreparationTime1.name = "recipePreparationTime";
	recipePreparationTime1.appearance = appearance19;   // Note: for this property a default value is defined.
	recipePreparationTime1.content = clientTemplate10;   // Note: for this property a default value is defined.
	recipePreparationTime1.renderMode = pages.TextRenderMode.Paragraph;

	var microflowSettings7 = pages.MicroflowSettings.create(model);
	microflowSettings7.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_ShowRecipe");

	var microflowClientAction4 = pages.MicroflowClientAction.create(model);
	microflowClientAction4.microflowSettings = microflowSettings7;   // Note: for this property a default value is defined.

	var noClientAction3 = pages.NoClientAction.create(model);

	var recipeList1 = pages.ListView.create(model);
	recipeList1.name = "recipeList";
	recipeList1.appearance = appearance16;   // Note: for this property a default value is defined.
	recipeList1.dataSource = microflowSource3;
	recipeList1.widgets.push(recipeName1);
	recipeList1.widgets.push(recipeDescription1);
	recipeList1.widgets.push(recipePreparationTime1);
	recipeList1.clickAction = microflowClientAction4;   // Note: for this property a default value is defined.
	recipeList1.pullDownAction = noClientAction3;   // Note: for this property a default value is defined.

	var noClientAction4 = pages.NoClientAction.create(model);

	var recipesPanel1 = pages.DivContainer.create(model);
	recipesPanel1.name = "recipesPanel";
	recipesPanel1.appearance = appearance12;   // Note: for this property a default value is defined.
	recipesPanel1.widgets.push(recipesHeader1);
	recipesPanel1.widgets.push(addRecipeButton1);
	recipesPanel1.widgets.push(selectedCategory1);
	recipesPanel1.widgets.push(recipeList1);
	recipesPanel1.onClickAction = noClientAction4;   // Note: for this property a default value is defined.

	var appearance20 = pages.Appearance.create(model);

	var layoutGridColumn3 = pages.LayoutGridColumn.create(model);
	layoutGridColumn3.weight = 9;
	layoutGridColumn3.widgets.push(recipesPanel1);
	layoutGridColumn3.appearance = appearance20;   // Note: for this property a default value is defined.

	var appearance21 = pages.Appearance.create(model);

	var layoutGridRow2 = pages.LayoutGridRow.create(model);
	layoutGridRow2.columns.push(layoutGridColumn2);
	layoutGridRow2.columns.push(layoutGridColumn3);
	layoutGridRow2.appearance = appearance21;   // Note: for this property a default value is defined.

	var homeGrid1 = pages.LayoutGrid.create(model);
	homeGrid1.name = "homeGrid";
	homeGrid1.appearance = appearance2;   // Note: for this property a default value is defined.
	homeGrid1.rows.push(layoutGridRow1);
	homeGrid1.rows.push(layoutGridRow2);

	var text23 = texts.Text.create(model);

	var homeContextDataView1 = pages.DataView.create(model);
	homeContextDataView1.name = "homeContextDataView";
	homeContextDataView1.appearance = appearance1;   // Note: for this property a default value is defined.
	homeContextDataView1.dataSource = microflowSource1;
	homeContextDataView1.widgets.push(homeGrid1);
	homeContextDataView1.editability = pages.EditableEnum.Never;
	homeContextDataView1.showFooter = false;
	homeContextDataView1.noEntityMessage = text23;   // Note: for this property a default value is defined.

	var layoutCallArgument1 = pages.LayoutCallArgument.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	layoutCallArgument1.__parameter.updateWithRawValue("Atlas_Core.Atlas_TopBar.Main");
	layoutCallArgument1.widgets.push(homeContextDataView1);

	var layoutCall1 = pages.LayoutCall.create(model);
	layoutCall1.layout = model.findLayoutByQualifiedName("Atlas_Core.Atlas_TopBar");
	layoutCall1.arguments.push(layoutCallArgument1);

	var translation11 = texts.Translation.create(model);
	translation11.languageCode = "en_US";
	translation11.text = "Homepage";

	var text24 = texts.Text.create(model);
	text24.translations.push(translation11);

	var appearance22 = pages.Appearance.create(model);

	var home_Web1 = pages.Page.createIn(unit);
	home_Web1.name = "Home_Web";
	home_Web1.canvasWidth = 1200;
	home_Web1.layoutCall = layoutCall1;   // Note: for this property a default value is defined.
	home_Web1.title = text24;   // Note: for this property a default value is defined.
	home_Web1.appearance = appearance22;   // Note: for this property a default value is defined.
	home_Web1.allowedRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));
	home_Web1.autofocus = pages.Autofocus.DesktopOnly;

	pageVariable1.widget = homeContextDataView1;

})