(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "3dfa47c0-8e16-4379-b055-75dad28f9633" of type Pages$Page
	 * in working copy "mendix-recipes"
	 * on 10-9-2026.
	 */

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");

	var newRecipe1 = pages.PageParameter.create(model);
	newRecipe1.name = "NewRecipe";
	newRecipe1.parameterType = objectType1;   // Note: for this property a default value is defined.

	var objectType2 = datatypes.ObjectType.create(model);
	objectType2.entity = model.findEntityByQualifiedName("MyFirstModule.HomeContext");

	var homeContext1 = pages.PageParameter.create(model);
	homeContext1.name = "HomeContext";
	homeContext1.parameterType = objectType2;   // Note: for this property a default value is defined.

	var appearance1 = pages.Appearance.create(model);
	appearance1.class = "recipe-form";

	var directEntityRef1 = domainmodels.DirectEntityRef.create(model);
	directEntityRef1.entity = model.findEntityByQualifiedName("MyFirstModule.NewRecipe");

	var pageVariable1 = pages.PageVariable.create(model);

	var dataViewSource1 = pages.DataViewSource.create(model);
	dataViewSource1.entityRef = directEntityRef1;
	dataViewSource1.sourceVariable = pageVariable1;

	var appearance2 = pages.Appearance.create(model);

	var appearance3 = pages.Appearance.create(model);

	var translation1 = texts.Translation.create(model);
	translation1.languageCode = "en_US";
	translation1.text = "Add a recipe";

	var text1 = texts.Text.create(model);
	text1.translations.push(translation1);

	var text2 = texts.Text.create(model);

	var clientTemplate1 = pages.ClientTemplate.create(model);
	clientTemplate1.template = text1;   // Note: for this property a default value is defined.
	clientTemplate1.fallback = text2;   // Note: for this property a default value is defined.

	var formHeader1 = pages.DynamicText.create(model);
	formHeader1.name = "formHeader";
	formHeader1.appearance = appearance3;   // Note: for this property a default value is defined.
	formHeader1.content = clientTemplate1;   // Note: for this property a default value is defined.
	formHeader1.renderMode = pages.TextRenderMode.H1;

	var appearance4 = pages.Appearance.create(model);

	var layoutGridColumn1 = pages.LayoutGridColumn.create(model);
	layoutGridColumn1.weight = -1;
	layoutGridColumn1.widgets.push(formHeader1);
	layoutGridColumn1.appearance = appearance4;   // Note: for this property a default value is defined.

	var appearance5 = pages.Appearance.create(model);

	var layoutGridRow1 = pages.LayoutGridRow.create(model);
	layoutGridRow1.columns.push(layoutGridColumn1);
	layoutGridRow1.appearance = appearance5;   // Note: for this property a default value is defined.

	var appearance6 = pages.Appearance.create(model);
	appearance6.class = "recipes-panel";

	var appearance7 = pages.Appearance.create(model);

	var translation2 = texts.Translation.create(model);
	translation2.languageCode = "en_US";
	translation2.text = "Recipe";

	var text3 = texts.Text.create(model);
	text3.translations.push(translation2);

	var text4 = texts.Text.create(model);

	var clientTemplate2 = pages.ClientTemplate.create(model);
	clientTemplate2.template = text3;   // Note: for this property a default value is defined.
	clientTemplate2.fallback = text4;   // Note: for this property a default value is defined.

	var recipeFieldsHeader1 = pages.DynamicText.create(model);
	recipeFieldsHeader1.name = "recipeFieldsHeader";
	recipeFieldsHeader1.appearance = appearance7;   // Note: for this property a default value is defined.
	recipeFieldsHeader1.content = clientTemplate2;   // Note: for this property a default value is defined.
	recipeFieldsHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance8 = pages.Appearance.create(model);

	var translation3 = texts.Translation.create(model);
	translation3.languageCode = "en_US";
	translation3.text = "Name";

	var text5 = texts.Text.create(model);
	text5.translations.push(translation3);

	var text6 = texts.Text.create(model);

	var clientTemplate3 = pages.ClientTemplate.create(model);
	clientTemplate3.template = text5;   // Note: for this property a default value is defined.
	clientTemplate3.fallback = text6;   // Note: for this property a default value is defined.

	var attributeRef1 = domainmodels.AttributeRef.create(model);
	attributeRef1.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Name");

	var text7 = texts.Text.create(model);

	var widgetValidation1 = pages.WidgetValidation.create(model);
	widgetValidation1.message = text7;   // Note: for this property a default value is defined.

	var noClientAction1 = pages.NoClientAction.create(model);

	var noClientAction2 = pages.NoClientAction.create(model);

	var noClientAction3 = pages.NoClientAction.create(model);

	var translation4 = texts.Translation.create(model);
	translation4.languageCode = "en_US";

	var text8 = texts.Text.create(model);
	text8.translations.push(translation4);

	var text9 = texts.Text.create(model);

	var clientTemplate4 = pages.ClientTemplate.create(model);
	clientTemplate4.template = text8;   // Note: for this property a default value is defined.
	clientTemplate4.fallback = text9;   // Note: for this property a default value is defined.

	var formattingInfo1 = pages.FormattingInfo.create(model);

	var noClientAction4 = pages.NoClientAction.create(model);

	var nameInput1 = pages.TextBox.create(model);
	nameInput1.name = "nameInput";
	nameInput1.appearance = appearance8;   // Note: for this property a default value is defined.
	nameInput1.labelTemplate = clientTemplate3;
	nameInput1.attributeRef = attributeRef1;
	nameInput1.validation = widgetValidation1;   // Note: for this property a default value is defined.
	nameInput1.onChangeAction = noClientAction1;   // Note: for this property a default value is defined.
	nameInput1.onEnterAction = noClientAction2;   // Note: for this property a default value is defined.
	nameInput1.onLeaveAction = noClientAction3;   // Note: for this property a default value is defined.
	nameInput1.placeholderTemplate = clientTemplate4;   // Note: for this property a default value is defined.
	nameInput1.formattingInfo = formattingInfo1;   // Note: for this property a default value is defined.
	nameInput1.onEnterKeyPressAction = noClientAction4;   // Note: for this property a default value is defined.

	var appearance9 = pages.Appearance.create(model);

	var translation5 = texts.Translation.create(model);
	translation5.languageCode = "en_US";
	translation5.text = "Description";

	var text10 = texts.Text.create(model);
	text10.translations.push(translation5);

	var text11 = texts.Text.create(model);

	var clientTemplate5 = pages.ClientTemplate.create(model);
	clientTemplate5.template = text10;   // Note: for this property a default value is defined.
	clientTemplate5.fallback = text11;   // Note: for this property a default value is defined.

	var attributeRef2 = domainmodels.AttributeRef.create(model);
	attributeRef2.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Description");

	var text12 = texts.Text.create(model);

	var widgetValidation2 = pages.WidgetValidation.create(model);
	widgetValidation2.message = text12;   // Note: for this property a default value is defined.

	var noClientAction5 = pages.NoClientAction.create(model);

	var noClientAction6 = pages.NoClientAction.create(model);

	var noClientAction7 = pages.NoClientAction.create(model);

	var translation6 = texts.Translation.create(model);
	translation6.languageCode = "en_US";

	var text13 = texts.Text.create(model);
	text13.translations.push(translation6);

	var text14 = texts.Text.create(model);

	var clientTemplate6 = pages.ClientTemplate.create(model);
	clientTemplate6.template = text13;   // Note: for this property a default value is defined.
	clientTemplate6.fallback = text14;   // Note: for this property a default value is defined.

	var text15 = texts.Text.create(model);

	var text16 = texts.Text.create(model);

	var descriptionInput1 = pages.TextArea.create(model);
	descriptionInput1.name = "descriptionInput";
	descriptionInput1.appearance = appearance9;   // Note: for this property a default value is defined.
	descriptionInput1.labelTemplate = clientTemplate5;
	descriptionInput1.attributeRef = attributeRef2;
	descriptionInput1.validation = widgetValidation2;   // Note: for this property a default value is defined.
	descriptionInput1.onChangeAction = noClientAction5;   // Note: for this property a default value is defined.
	descriptionInput1.onEnterAction = noClientAction6;   // Note: for this property a default value is defined.
	descriptionInput1.onLeaveAction = noClientAction7;   // Note: for this property a default value is defined.
	descriptionInput1.placeholderTemplate = clientTemplate6;   // Note: for this property a default value is defined.
	descriptionInput1.counterMessage = text15;   // Note: for this property a default value is defined.
	descriptionInput1.textTooLongMessage = text16;   // Note: for this property a default value is defined.

	var appearance10 = pages.Appearance.create(model);

	var translation7 = texts.Translation.create(model);
	translation7.languageCode = "en_US";
	translation7.text = "Preparation time (minutes)";

	var text17 = texts.Text.create(model);
	text17.translations.push(translation7);

	var text18 = texts.Text.create(model);

	var clientTemplate7 = pages.ClientTemplate.create(model);
	clientTemplate7.template = text17;   // Note: for this property a default value is defined.
	clientTemplate7.fallback = text18;   // Note: for this property a default value is defined.

	var attributeRef3 = domainmodels.AttributeRef.create(model);
	attributeRef3.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PreparationTimeInMinutes");

	var text19 = texts.Text.create(model);

	var widgetValidation3 = pages.WidgetValidation.create(model);
	widgetValidation3.message = text19;   // Note: for this property a default value is defined.

	var noClientAction8 = pages.NoClientAction.create(model);

	var noClientAction9 = pages.NoClientAction.create(model);

	var noClientAction10 = pages.NoClientAction.create(model);

	var translation8 = texts.Translation.create(model);
	translation8.languageCode = "en_US";

	var text20 = texts.Text.create(model);
	text20.translations.push(translation8);

	var text21 = texts.Text.create(model);

	var clientTemplate8 = pages.ClientTemplate.create(model);
	clientTemplate8.template = text20;   // Note: for this property a default value is defined.
	clientTemplate8.fallback = text21;   // Note: for this property a default value is defined.

	var formattingInfo2 = pages.FormattingInfo.create(model);

	var noClientAction11 = pages.NoClientAction.create(model);

	var preparationTimeInput1 = pages.TextBox.create(model);
	preparationTimeInput1.name = "preparationTimeInput";
	preparationTimeInput1.appearance = appearance10;   // Note: for this property a default value is defined.
	preparationTimeInput1.labelTemplate = clientTemplate7;
	preparationTimeInput1.attributeRef = attributeRef3;
	preparationTimeInput1.validation = widgetValidation3;   // Note: for this property a default value is defined.
	preparationTimeInput1.onChangeAction = noClientAction8;   // Note: for this property a default value is defined.
	preparationTimeInput1.onEnterAction = noClientAction9;   // Note: for this property a default value is defined.
	preparationTimeInput1.onLeaveAction = noClientAction10;   // Note: for this property a default value is defined.
	preparationTimeInput1.placeholderTemplate = clientTemplate8;   // Note: for this property a default value is defined.
	preparationTimeInput1.formattingInfo = formattingInfo2;   // Note: for this property a default value is defined.
	preparationTimeInput1.onEnterKeyPressAction = noClientAction11;   // Note: for this property a default value is defined.

	var appearance11 = pages.Appearance.create(model);

	var translation9 = texts.Translation.create(model);
	translation9.languageCode = "en_US";
	translation9.text = "Author";

	var text22 = texts.Text.create(model);
	text22.translations.push(translation9);

	var text23 = texts.Text.create(model);

	var clientTemplate9 = pages.ClientTemplate.create(model);
	clientTemplate9.template = text22;   // Note: for this property a default value is defined.
	clientTemplate9.fallback = text23;   // Note: for this property a default value is defined.

	var attributeRef4 = domainmodels.AttributeRef.create(model);
	attributeRef4.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.Author");

	var text24 = texts.Text.create(model);

	var widgetValidation4 = pages.WidgetValidation.create(model);
	widgetValidation4.message = text24;   // Note: for this property a default value is defined.

	var noClientAction12 = pages.NoClientAction.create(model);

	var noClientAction13 = pages.NoClientAction.create(model);

	var noClientAction14 = pages.NoClientAction.create(model);

	var translation10 = texts.Translation.create(model);
	translation10.languageCode = "en_US";

	var text25 = texts.Text.create(model);
	text25.translations.push(translation10);

	var text26 = texts.Text.create(model);

	var clientTemplate10 = pages.ClientTemplate.create(model);
	clientTemplate10.template = text25;   // Note: for this property a default value is defined.
	clientTemplate10.fallback = text26;   // Note: for this property a default value is defined.

	var formattingInfo3 = pages.FormattingInfo.create(model);

	var noClientAction15 = pages.NoClientAction.create(model);

	var authorInput1 = pages.TextBox.create(model);
	authorInput1.name = "authorInput";
	authorInput1.appearance = appearance11;   // Note: for this property a default value is defined.
	authorInput1.labelTemplate = clientTemplate9;
	authorInput1.attributeRef = attributeRef4;
	authorInput1.validation = widgetValidation4;   // Note: for this property a default value is defined.
	authorInput1.onChangeAction = noClientAction12;   // Note: for this property a default value is defined.
	authorInput1.onEnterAction = noClientAction13;   // Note: for this property a default value is defined.
	authorInput1.onLeaveAction = noClientAction14;   // Note: for this property a default value is defined.
	authorInput1.placeholderTemplate = clientTemplate10;   // Note: for this property a default value is defined.
	authorInput1.formattingInfo = formattingInfo3;   // Note: for this property a default value is defined.
	authorInput1.onEnterKeyPressAction = noClientAction15;   // Note: for this property a default value is defined.

	var appearance12 = pages.Appearance.create(model);

	var translation11 = texts.Translation.create(model);
	translation11.languageCode = "en_US";
	translation11.text = "Posted to";

	var text27 = texts.Text.create(model);
	text27.translations.push(translation11);

	var text28 = texts.Text.create(model);

	var clientTemplate11 = pages.ClientTemplate.create(model);
	clientTemplate11.template = text27;   // Note: for this property a default value is defined.
	clientTemplate11.fallback = text28;   // Note: for this property a default value is defined.

	var attributeRef5 = domainmodels.AttributeRef.create(model);
	attributeRef5.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedTo");

	var text29 = texts.Text.create(model);

	var widgetValidation5 = pages.WidgetValidation.create(model);
	widgetValidation5.message = text29;   // Note: for this property a default value is defined.

	var noClientAction16 = pages.NoClientAction.create(model);

	var noClientAction17 = pages.NoClientAction.create(model);

	var noClientAction18 = pages.NoClientAction.create(model);

	var translation12 = texts.Translation.create(model);
	translation12.languageCode = "en_US";

	var text30 = texts.Text.create(model);
	text30.translations.push(translation12);

	var text31 = texts.Text.create(model);

	var clientTemplate12 = pages.ClientTemplate.create(model);
	clientTemplate12.template = text30;   // Note: for this property a default value is defined.
	clientTemplate12.fallback = text31;   // Note: for this property a default value is defined.

	var formattingInfo4 = pages.FormattingInfo.create(model);

	var noClientAction19 = pages.NoClientAction.create(model);

	var postedToInput1 = pages.TextBox.create(model);
	postedToInput1.name = "postedToInput";
	postedToInput1.appearance = appearance12;   // Note: for this property a default value is defined.
	postedToInput1.labelTemplate = clientTemplate11;
	postedToInput1.attributeRef = attributeRef5;
	postedToInput1.validation = widgetValidation5;   // Note: for this property a default value is defined.
	postedToInput1.onChangeAction = noClientAction16;   // Note: for this property a default value is defined.
	postedToInput1.onEnterAction = noClientAction17;   // Note: for this property a default value is defined.
	postedToInput1.onLeaveAction = noClientAction18;   // Note: for this property a default value is defined.
	postedToInput1.placeholderTemplate = clientTemplate12;   // Note: for this property a default value is defined.
	postedToInput1.formattingInfo = formattingInfo4;   // Note: for this property a default value is defined.
	postedToInput1.onEnterKeyPressAction = noClientAction19;   // Note: for this property a default value is defined.

	var appearance13 = pages.Appearance.create(model);

	var translation13 = texts.Translation.create(model);
	translation13.languageCode = "en_US";
	translation13.text = "Posted at";

	var text32 = texts.Text.create(model);
	text32.translations.push(translation13);

	var text33 = texts.Text.create(model);

	var clientTemplate13 = pages.ClientTemplate.create(model);
	clientTemplate13.template = text32;   // Note: for this property a default value is defined.
	clientTemplate13.fallback = text33;   // Note: for this property a default value is defined.

	var attributeRef6 = domainmodels.AttributeRef.create(model);
	attributeRef6.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipe.PostedAt");

	var text34 = texts.Text.create(model);

	var widgetValidation6 = pages.WidgetValidation.create(model);
	widgetValidation6.message = text34;   // Note: for this property a default value is defined.

	var noClientAction20 = pages.NoClientAction.create(model);

	var noClientAction21 = pages.NoClientAction.create(model);

	var noClientAction22 = pages.NoClientAction.create(model);

	var translation14 = texts.Translation.create(model);
	translation14.languageCode = "en_US";

	var text35 = texts.Text.create(model);
	text35.translations.push(translation14);

	var text36 = texts.Text.create(model);

	var clientTemplate14 = pages.ClientTemplate.create(model);
	clientTemplate14.template = text35;   // Note: for this property a default value is defined.
	clientTemplate14.fallback = text36;   // Note: for this property a default value is defined.

	var formattingInfo5 = pages.FormattingInfo.create(model);

	var postedAtInput1 = pages.DatePicker.create(model);
	postedAtInput1.name = "postedAtInput";
	postedAtInput1.appearance = appearance13;   // Note: for this property a default value is defined.
	postedAtInput1.labelTemplate = clientTemplate13;
	postedAtInput1.attributeRef = attributeRef6;
	postedAtInput1.validation = widgetValidation6;   // Note: for this property a default value is defined.
	postedAtInput1.onChangeAction = noClientAction20;   // Note: for this property a default value is defined.
	postedAtInput1.onEnterAction = noClientAction21;   // Note: for this property a default value is defined.
	postedAtInput1.onLeaveAction = noClientAction22;   // Note: for this property a default value is defined.
	postedAtInput1.placeholderTemplate = clientTemplate14;   // Note: for this property a default value is defined.
	postedAtInput1.formattingInfo = formattingInfo5;   // Note: for this property a default value is defined.

	var noClientAction23 = pages.NoClientAction.create(model);

	var recipeFieldsPanel1 = pages.DivContainer.create(model);
	recipeFieldsPanel1.name = "recipeFieldsPanel";
	recipeFieldsPanel1.appearance = appearance6;   // Note: for this property a default value is defined.
	recipeFieldsPanel1.widgets.push(recipeFieldsHeader1);
	recipeFieldsPanel1.widgets.push(nameInput1);
	recipeFieldsPanel1.widgets.push(descriptionInput1);
	recipeFieldsPanel1.widgets.push(preparationTimeInput1);
	recipeFieldsPanel1.widgets.push(authorInput1);
	recipeFieldsPanel1.widgets.push(postedToInput1);
	recipeFieldsPanel1.widgets.push(postedAtInput1);
	recipeFieldsPanel1.onClickAction = noClientAction23;   // Note: for this property a default value is defined.

	var appearance14 = pages.Appearance.create(model);

	var layoutGridColumn2 = pages.LayoutGridColumn.create(model);
	layoutGridColumn2.weight = 6;
	layoutGridColumn2.widgets.push(recipeFieldsPanel1);
	layoutGridColumn2.appearance = appearance14;   // Note: for this property a default value is defined.

	var appearance15 = pages.Appearance.create(model);
	appearance15.class = "recipes-panel";

	var appearance16 = pages.Appearance.create(model);

	var translation15 = texts.Translation.create(model);
	translation15.languageCode = "en_US";
	translation15.text = "Steps";

	var text37 = texts.Text.create(model);
	text37.translations.push(translation15);

	var text38 = texts.Text.create(model);

	var clientTemplate15 = pages.ClientTemplate.create(model);
	clientTemplate15.template = text37;   // Note: for this property a default value is defined.
	clientTemplate15.fallback = text38;   // Note: for this property a default value is defined.

	var stepHeader1 = pages.DynamicText.create(model);
	stepHeader1.name = "stepHeader";
	stepHeader1.appearance = appearance16;   // Note: for this property a default value is defined.
	stepHeader1.content = clientTemplate15;   // Note: for this property a default value is defined.
	stepHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance17 = pages.Appearance.create(model);
	appearance17.class = "recipe-form-list";

	var pageVariable2 = pages.PageVariable.create(model);

	var microflowParameterMapping1 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping1.__parameter.updateWithRawValue("MyFirstModule.DS_NewRecipeSteps.NewRecipe");
	microflowParameterMapping1.variable = pageVariable2;

	var microflowSettings1 = pages.MicroflowSettings.create(model);
	microflowSettings1.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_NewRecipeSteps");
	microflowSettings1.parameterMappings.push(microflowParameterMapping1);

	var microflowSource1 = pages.MicroflowSource.create(model);
	microflowSource1.microflowSettings = microflowSettings1;   // Note: for this property a default value is defined.

	var appearance18 = pages.Appearance.create(model);

	var translation16 = texts.Translation.create(model);
	translation16.languageCode = "en_US";
	translation16.text = "Step";

	var text39 = texts.Text.create(model);
	text39.translations.push(translation16);

	var text40 = texts.Text.create(model);

	var clientTemplate16 = pages.ClientTemplate.create(model);
	clientTemplate16.template = text39;   // Note: for this property a default value is defined.
	clientTemplate16.fallback = text40;   // Note: for this property a default value is defined.

	var attributeRef7 = domainmodels.AttributeRef.create(model);
	attributeRef7.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeStep.Description");

	var text41 = texts.Text.create(model);

	var widgetValidation7 = pages.WidgetValidation.create(model);
	widgetValidation7.message = text41;   // Note: for this property a default value is defined.

	var noClientAction24 = pages.NoClientAction.create(model);

	var noClientAction25 = pages.NoClientAction.create(model);

	var noClientAction26 = pages.NoClientAction.create(model);

	var translation17 = texts.Translation.create(model);
	translation17.languageCode = "en_US";

	var text42 = texts.Text.create(model);
	text42.translations.push(translation17);

	var text43 = texts.Text.create(model);

	var clientTemplate17 = pages.ClientTemplate.create(model);
	clientTemplate17.template = text42;   // Note: for this property a default value is defined.
	clientTemplate17.fallback = text43;   // Note: for this property a default value is defined.

	var formattingInfo6 = pages.FormattingInfo.create(model);

	var noClientAction27 = pages.NoClientAction.create(model);

	var stepDescriptionInput1 = pages.TextBox.create(model);
	stepDescriptionInput1.name = "stepDescriptionInput";
	stepDescriptionInput1.appearance = appearance18;   // Note: for this property a default value is defined.
	stepDescriptionInput1.labelTemplate = clientTemplate16;
	stepDescriptionInput1.attributeRef = attributeRef7;
	stepDescriptionInput1.validation = widgetValidation7;   // Note: for this property a default value is defined.
	stepDescriptionInput1.onChangeAction = noClientAction24;   // Note: for this property a default value is defined.
	stepDescriptionInput1.onEnterAction = noClientAction25;   // Note: for this property a default value is defined.
	stepDescriptionInput1.onLeaveAction = noClientAction26;   // Note: for this property a default value is defined.
	stepDescriptionInput1.placeholderTemplate = clientTemplate17;   // Note: for this property a default value is defined.
	stepDescriptionInput1.formattingInfo = formattingInfo6;   // Note: for this property a default value is defined.
	stepDescriptionInput1.onEnterKeyPressAction = noClientAction27;   // Note: for this property a default value is defined.

	var appearance19 = pages.Appearance.create(model);

	var translation18 = texts.Translation.create(model);
	translation18.languageCode = "en_US";
	translation18.text = "Remove";

	var text44 = texts.Text.create(model);
	text44.translations.push(translation18);

	var text45 = texts.Text.create(model);

	var clientTemplate18 = pages.ClientTemplate.create(model);
	clientTemplate18.template = text44;   // Note: for this property a default value is defined.
	clientTemplate18.fallback = text45;   // Note: for this property a default value is defined.

	var text46 = texts.Text.create(model);

	var microflowSettings2 = pages.MicroflowSettings.create(model);
	microflowSettings2.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_RemoveStep");

	var microflowClientAction1 = pages.MicroflowClientAction.create(model);
	microflowClientAction1.microflowSettings = microflowSettings2;   // Note: for this property a default value is defined.

	var stepRemoveButton1 = pages.ActionButton.create(model);
	stepRemoveButton1.name = "stepRemoveButton";
	stepRemoveButton1.appearance = appearance19;   // Note: for this property a default value is defined.
	stepRemoveButton1.caption = clientTemplate18;   // Note: for this property a default value is defined.
	stepRemoveButton1.tooltip = text46;   // Note: for this property a default value is defined.
	stepRemoveButton1.renderType = pages.RenderType.Link;
	stepRemoveButton1.action = microflowClientAction1;   // Note: for this property a default value is defined.

	var noClientAction28 = pages.NoClientAction.create(model);

	var noClientAction29 = pages.NoClientAction.create(model);

	var stepList1 = pages.ListView.create(model);
	stepList1.name = "stepList";
	stepList1.appearance = appearance17;   // Note: for this property a default value is defined.
	stepList1.dataSource = microflowSource1;
	stepList1.widgets.push(stepDescriptionInput1);
	stepList1.widgets.push(stepRemoveButton1);
	stepList1.clickAction = noClientAction28;   // Note: for this property a default value is defined.
	stepList1.editable = true;
	stepList1.pullDownAction = noClientAction29;   // Note: for this property a default value is defined.

	var appearance20 = pages.Appearance.create(model);

	var translation19 = texts.Translation.create(model);
	translation19.languageCode = "en_US";
	translation19.text = "Add a step";

	var text47 = texts.Text.create(model);
	text47.translations.push(translation19);

	var text48 = texts.Text.create(model);

	var clientTemplate19 = pages.ClientTemplate.create(model);
	clientTemplate19.template = text47;   // Note: for this property a default value is defined.
	clientTemplate19.fallback = text48;   // Note: for this property a default value is defined.

	var text49 = texts.Text.create(model);

	var microflowSettings3 = pages.MicroflowSettings.create(model);
	microflowSettings3.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_AddStep");

	var microflowClientAction2 = pages.MicroflowClientAction.create(model);
	microflowClientAction2.microflowSettings = microflowSettings3;   // Note: for this property a default value is defined.

	var stepAddButton1 = pages.ActionButton.create(model);
	stepAddButton1.name = "stepAddButton";
	stepAddButton1.appearance = appearance20;   // Note: for this property a default value is defined.
	stepAddButton1.caption = clientTemplate19;   // Note: for this property a default value is defined.
	stepAddButton1.tooltip = text49;   // Note: for this property a default value is defined.
	stepAddButton1.renderType = pages.RenderType.Link;
	stepAddButton1.action = microflowClientAction2;   // Note: for this property a default value is defined.

	var noClientAction30 = pages.NoClientAction.create(model);

	var stepPanel1 = pages.DivContainer.create(model);
	stepPanel1.name = "stepPanel";
	stepPanel1.appearance = appearance15;   // Note: for this property a default value is defined.
	stepPanel1.widgets.push(stepHeader1);
	stepPanel1.widgets.push(stepList1);
	stepPanel1.widgets.push(stepAddButton1);
	stepPanel1.onClickAction = noClientAction30;   // Note: for this property a default value is defined.

	var appearance21 = pages.Appearance.create(model);
	appearance21.class = "recipes-panel";

	var appearance22 = pages.Appearance.create(model);

	var translation20 = texts.Translation.create(model);
	translation20.languageCode = "en_US";
	translation20.text = "Ingredients";

	var text50 = texts.Text.create(model);
	text50.translations.push(translation20);

	var text51 = texts.Text.create(model);

	var clientTemplate20 = pages.ClientTemplate.create(model);
	clientTemplate20.template = text50;   // Note: for this property a default value is defined.
	clientTemplate20.fallback = text51;   // Note: for this property a default value is defined.

	var ingredientHeader1 = pages.DynamicText.create(model);
	ingredientHeader1.name = "ingredientHeader";
	ingredientHeader1.appearance = appearance22;   // Note: for this property a default value is defined.
	ingredientHeader1.content = clientTemplate20;   // Note: for this property a default value is defined.
	ingredientHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance23 = pages.Appearance.create(model);

	var translation21 = texts.Translation.create(model);
	translation21.languageCode = "en_US";
	translation21.text = "Units: LITER, CUP, TABLESPOON, TEASPOON, GRAM, POUND, PIECE, CAN, PACKAGE, JAR";

	var text52 = texts.Text.create(model);
	text52.translations.push(translation21);

	var text53 = texts.Text.create(model);

	var clientTemplate21 = pages.ClientTemplate.create(model);
	clientTemplate21.template = text52;   // Note: for this property a default value is defined.
	clientTemplate21.fallback = text53;   // Note: for this property a default value is defined.

	var ingredientHint1 = pages.DynamicText.create(model);
	ingredientHint1.name = "ingredientHint";
	ingredientHint1.appearance = appearance23;   // Note: for this property a default value is defined.
	ingredientHint1.content = clientTemplate21;   // Note: for this property a default value is defined.
	ingredientHint1.renderMode = pages.TextRenderMode.Paragraph;

	var appearance24 = pages.Appearance.create(model);
	appearance24.class = "recipe-form-list";

	var pageVariable3 = pages.PageVariable.create(model);

	var microflowParameterMapping2 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping2.__parameter.updateWithRawValue("MyFirstModule.DS_NewRecipeIngredients.NewRecipe");
	microflowParameterMapping2.variable = pageVariable3;

	var microflowSettings4 = pages.MicroflowSettings.create(model);
	microflowSettings4.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_NewRecipeIngredients");
	microflowSettings4.parameterMappings.push(microflowParameterMapping2);

	var microflowSource2 = pages.MicroflowSource.create(model);
	microflowSource2.microflowSettings = microflowSettings4;   // Note: for this property a default value is defined.

	var appearance25 = pages.Appearance.create(model);

	var translation22 = texts.Translation.create(model);
	translation22.languageCode = "en_US";
	translation22.text = "Quantity";

	var text54 = texts.Text.create(model);
	text54.translations.push(translation22);

	var text55 = texts.Text.create(model);

	var clientTemplate22 = pages.ClientTemplate.create(model);
	clientTemplate22.template = text54;   // Note: for this property a default value is defined.
	clientTemplate22.fallback = text55;   // Note: for this property a default value is defined.

	var attributeRef8 = domainmodels.AttributeRef.create(model);
	attributeRef8.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Quantity");

	var text56 = texts.Text.create(model);

	var widgetValidation8 = pages.WidgetValidation.create(model);
	widgetValidation8.message = text56;   // Note: for this property a default value is defined.

	var noClientAction31 = pages.NoClientAction.create(model);

	var noClientAction32 = pages.NoClientAction.create(model);

	var noClientAction33 = pages.NoClientAction.create(model);

	var translation23 = texts.Translation.create(model);
	translation23.languageCode = "en_US";

	var text57 = texts.Text.create(model);
	text57.translations.push(translation23);

	var text58 = texts.Text.create(model);

	var clientTemplate23 = pages.ClientTemplate.create(model);
	clientTemplate23.template = text57;   // Note: for this property a default value is defined.
	clientTemplate23.fallback = text58;   // Note: for this property a default value is defined.

	var formattingInfo7 = pages.FormattingInfo.create(model);

	var noClientAction34 = pages.NoClientAction.create(model);

	var ingredientQuantityInput1 = pages.TextBox.create(model);
	ingredientQuantityInput1.name = "ingredientQuantityInput";
	ingredientQuantityInput1.appearance = appearance25;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.labelTemplate = clientTemplate22;
	ingredientQuantityInput1.attributeRef = attributeRef8;
	ingredientQuantityInput1.validation = widgetValidation8;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.onChangeAction = noClientAction31;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.onEnterAction = noClientAction32;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.onLeaveAction = noClientAction33;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.placeholderTemplate = clientTemplate23;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.formattingInfo = formattingInfo7;   // Note: for this property a default value is defined.
	ingredientQuantityInput1.onEnterKeyPressAction = noClientAction34;   // Note: for this property a default value is defined.

	var appearance26 = pages.Appearance.create(model);

	var translation24 = texts.Translation.create(model);
	translation24.languageCode = "en_US";
	translation24.text = "Unit";

	var text59 = texts.Text.create(model);
	text59.translations.push(translation24);

	var text60 = texts.Text.create(model);

	var clientTemplate24 = pages.ClientTemplate.create(model);
	clientTemplate24.template = text59;   // Note: for this property a default value is defined.
	clientTemplate24.fallback = text60;   // Note: for this property a default value is defined.

	var attributeRef9 = domainmodels.AttributeRef.create(model);
	attributeRef9.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Unit");

	var text61 = texts.Text.create(model);

	var widgetValidation9 = pages.WidgetValidation.create(model);
	widgetValidation9.message = text61;   // Note: for this property a default value is defined.

	var noClientAction35 = pages.NoClientAction.create(model);

	var noClientAction36 = pages.NoClientAction.create(model);

	var noClientAction37 = pages.NoClientAction.create(model);

	var translation25 = texts.Translation.create(model);
	translation25.languageCode = "en_US";

	var text62 = texts.Text.create(model);
	text62.translations.push(translation25);

	var text63 = texts.Text.create(model);

	var clientTemplate25 = pages.ClientTemplate.create(model);
	clientTemplate25.template = text62;   // Note: for this property a default value is defined.
	clientTemplate25.fallback = text63;   // Note: for this property a default value is defined.

	var formattingInfo8 = pages.FormattingInfo.create(model);

	var noClientAction38 = pages.NoClientAction.create(model);

	var ingredientUnitInput1 = pages.TextBox.create(model);
	ingredientUnitInput1.name = "ingredientUnitInput";
	ingredientUnitInput1.appearance = appearance26;   // Note: for this property a default value is defined.
	ingredientUnitInput1.labelTemplate = clientTemplate24;
	ingredientUnitInput1.attributeRef = attributeRef9;
	ingredientUnitInput1.validation = widgetValidation9;   // Note: for this property a default value is defined.
	ingredientUnitInput1.onChangeAction = noClientAction35;   // Note: for this property a default value is defined.
	ingredientUnitInput1.onEnterAction = noClientAction36;   // Note: for this property a default value is defined.
	ingredientUnitInput1.onLeaveAction = noClientAction37;   // Note: for this property a default value is defined.
	ingredientUnitInput1.placeholderTemplate = clientTemplate25;   // Note: for this property a default value is defined.
	ingredientUnitInput1.formattingInfo = formattingInfo8;   // Note: for this property a default value is defined.
	ingredientUnitInput1.onEnterKeyPressAction = noClientAction38;   // Note: for this property a default value is defined.

	var appearance27 = pages.Appearance.create(model);

	var translation26 = texts.Translation.create(model);
	translation26.languageCode = "en_US";
	translation26.text = "Ingredient";

	var text64 = texts.Text.create(model);
	text64.translations.push(translation26);

	var text65 = texts.Text.create(model);

	var clientTemplate26 = pages.ClientTemplate.create(model);
	clientTemplate26.template = text64;   // Note: for this property a default value is defined.
	clientTemplate26.fallback = text65;   // Note: for this property a default value is defined.

	var attributeRef10 = domainmodels.AttributeRef.create(model);
	attributeRef10.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeIngredient.Name");

	var text66 = texts.Text.create(model);

	var widgetValidation10 = pages.WidgetValidation.create(model);
	widgetValidation10.message = text66;   // Note: for this property a default value is defined.

	var noClientAction39 = pages.NoClientAction.create(model);

	var noClientAction40 = pages.NoClientAction.create(model);

	var noClientAction41 = pages.NoClientAction.create(model);

	var translation27 = texts.Translation.create(model);
	translation27.languageCode = "en_US";

	var text67 = texts.Text.create(model);
	text67.translations.push(translation27);

	var text68 = texts.Text.create(model);

	var clientTemplate27 = pages.ClientTemplate.create(model);
	clientTemplate27.template = text67;   // Note: for this property a default value is defined.
	clientTemplate27.fallback = text68;   // Note: for this property a default value is defined.

	var formattingInfo9 = pages.FormattingInfo.create(model);

	var noClientAction42 = pages.NoClientAction.create(model);

	var ingredientNameInput1 = pages.TextBox.create(model);
	ingredientNameInput1.name = "ingredientNameInput";
	ingredientNameInput1.appearance = appearance27;   // Note: for this property a default value is defined.
	ingredientNameInput1.labelTemplate = clientTemplate26;
	ingredientNameInput1.attributeRef = attributeRef10;
	ingredientNameInput1.validation = widgetValidation10;   // Note: for this property a default value is defined.
	ingredientNameInput1.onChangeAction = noClientAction39;   // Note: for this property a default value is defined.
	ingredientNameInput1.onEnterAction = noClientAction40;   // Note: for this property a default value is defined.
	ingredientNameInput1.onLeaveAction = noClientAction41;   // Note: for this property a default value is defined.
	ingredientNameInput1.placeholderTemplate = clientTemplate27;   // Note: for this property a default value is defined.
	ingredientNameInput1.formattingInfo = formattingInfo9;   // Note: for this property a default value is defined.
	ingredientNameInput1.onEnterKeyPressAction = noClientAction42;   // Note: for this property a default value is defined.

	var appearance28 = pages.Appearance.create(model);

	var translation28 = texts.Translation.create(model);
	translation28.languageCode = "en_US";
	translation28.text = "Remove";

	var text69 = texts.Text.create(model);
	text69.translations.push(translation28);

	var text70 = texts.Text.create(model);

	var clientTemplate28 = pages.ClientTemplate.create(model);
	clientTemplate28.template = text69;   // Note: for this property a default value is defined.
	clientTemplate28.fallback = text70;   // Note: for this property a default value is defined.

	var text71 = texts.Text.create(model);

	var microflowSettings5 = pages.MicroflowSettings.create(model);
	microflowSettings5.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_RemoveIngredient");

	var microflowClientAction3 = pages.MicroflowClientAction.create(model);
	microflowClientAction3.microflowSettings = microflowSettings5;   // Note: for this property a default value is defined.

	var ingredientRemoveButton1 = pages.ActionButton.create(model);
	ingredientRemoveButton1.name = "ingredientRemoveButton";
	ingredientRemoveButton1.appearance = appearance28;   // Note: for this property a default value is defined.
	ingredientRemoveButton1.caption = clientTemplate28;   // Note: for this property a default value is defined.
	ingredientRemoveButton1.tooltip = text71;   // Note: for this property a default value is defined.
	ingredientRemoveButton1.renderType = pages.RenderType.Link;
	ingredientRemoveButton1.action = microflowClientAction3;   // Note: for this property a default value is defined.

	var noClientAction43 = pages.NoClientAction.create(model);

	var noClientAction44 = pages.NoClientAction.create(model);

	var ingredientList1 = pages.ListView.create(model);
	ingredientList1.name = "ingredientList";
	ingredientList1.appearance = appearance24;   // Note: for this property a default value is defined.
	ingredientList1.dataSource = microflowSource2;
	ingredientList1.widgets.push(ingredientQuantityInput1);
	ingredientList1.widgets.push(ingredientUnitInput1);
	ingredientList1.widgets.push(ingredientNameInput1);
	ingredientList1.widgets.push(ingredientRemoveButton1);
	ingredientList1.clickAction = noClientAction43;   // Note: for this property a default value is defined.
	ingredientList1.editable = true;
	ingredientList1.pullDownAction = noClientAction44;   // Note: for this property a default value is defined.

	var appearance29 = pages.Appearance.create(model);

	var translation29 = texts.Translation.create(model);
	translation29.languageCode = "en_US";
	translation29.text = "Add an ingredient";

	var text72 = texts.Text.create(model);
	text72.translations.push(translation29);

	var text73 = texts.Text.create(model);

	var clientTemplate29 = pages.ClientTemplate.create(model);
	clientTemplate29.template = text72;   // Note: for this property a default value is defined.
	clientTemplate29.fallback = text73;   // Note: for this property a default value is defined.

	var text74 = texts.Text.create(model);

	var microflowSettings6 = pages.MicroflowSettings.create(model);
	microflowSettings6.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_AddIngredient");

	var microflowClientAction4 = pages.MicroflowClientAction.create(model);
	microflowClientAction4.microflowSettings = microflowSettings6;   // Note: for this property a default value is defined.

	var ingredientAddButton1 = pages.ActionButton.create(model);
	ingredientAddButton1.name = "ingredientAddButton";
	ingredientAddButton1.appearance = appearance29;   // Note: for this property a default value is defined.
	ingredientAddButton1.caption = clientTemplate29;   // Note: for this property a default value is defined.
	ingredientAddButton1.tooltip = text74;   // Note: for this property a default value is defined.
	ingredientAddButton1.renderType = pages.RenderType.Link;
	ingredientAddButton1.action = microflowClientAction4;   // Note: for this property a default value is defined.

	var noClientAction45 = pages.NoClientAction.create(model);

	var ingredientPanel1 = pages.DivContainer.create(model);
	ingredientPanel1.name = "ingredientPanel";
	ingredientPanel1.appearance = appearance21;   // Note: for this property a default value is defined.
	ingredientPanel1.widgets.push(ingredientHeader1);
	ingredientPanel1.widgets.push(ingredientHint1);
	ingredientPanel1.widgets.push(ingredientList1);
	ingredientPanel1.widgets.push(ingredientAddButton1);
	ingredientPanel1.onClickAction = noClientAction45;   // Note: for this property a default value is defined.

	var appearance30 = pages.Appearance.create(model);
	appearance30.class = "recipes-panel";

	var appearance31 = pages.Appearance.create(model);

	var translation30 = texts.Translation.create(model);
	translation30.languageCode = "en_US";
	translation30.text = "Categories";

	var text75 = texts.Text.create(model);
	text75.translations.push(translation30);

	var text76 = texts.Text.create(model);

	var clientTemplate30 = pages.ClientTemplate.create(model);
	clientTemplate30.template = text75;   // Note: for this property a default value is defined.
	clientTemplate30.fallback = text76;   // Note: for this property a default value is defined.

	var recipeCategoryHeader1 = pages.DynamicText.create(model);
	recipeCategoryHeader1.name = "recipeCategoryHeader";
	recipeCategoryHeader1.appearance = appearance31;   // Note: for this property a default value is defined.
	recipeCategoryHeader1.content = clientTemplate30;   // Note: for this property a default value is defined.
	recipeCategoryHeader1.renderMode = pages.TextRenderMode.H2;

	var appearance32 = pages.Appearance.create(model);
	appearance32.class = "recipe-form-list";

	var pageVariable4 = pages.PageVariable.create(model);

	var microflowParameterMapping3 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping3.__parameter.updateWithRawValue("MyFirstModule.DS_NewRecipeCategories.NewRecipe");
	microflowParameterMapping3.variable = pageVariable4;

	var microflowSettings7 = pages.MicroflowSettings.create(model);
	microflowSettings7.microflow = model.findMicroflowByQualifiedName("MyFirstModule.DS_NewRecipeCategories");
	microflowSettings7.parameterMappings.push(microflowParameterMapping3);

	var microflowSource3 = pages.MicroflowSource.create(model);
	microflowSource3.microflowSettings = microflowSettings7;   // Note: for this property a default value is defined.

	var appearance33 = pages.Appearance.create(model);

	var translation31 = texts.Translation.create(model);
	translation31.languageCode = "en_US";
	translation31.text = "Category";

	var text77 = texts.Text.create(model);
	text77.translations.push(translation31);

	var text78 = texts.Text.create(model);

	var clientTemplate31 = pages.ClientTemplate.create(model);
	clientTemplate31.template = text77;   // Note: for this property a default value is defined.
	clientTemplate31.fallback = text78;   // Note: for this property a default value is defined.

	var attributeRef11 = domainmodels.AttributeRef.create(model);
	attributeRef11.attribute = model.findAttributeByQualifiedName("MyFirstModule.NewRecipeCategory.Name");

	var text79 = texts.Text.create(model);

	var widgetValidation11 = pages.WidgetValidation.create(model);
	widgetValidation11.message = text79;   // Note: for this property a default value is defined.

	var noClientAction46 = pages.NoClientAction.create(model);

	var noClientAction47 = pages.NoClientAction.create(model);

	var noClientAction48 = pages.NoClientAction.create(model);

	var translation32 = texts.Translation.create(model);
	translation32.languageCode = "en_US";

	var text80 = texts.Text.create(model);
	text80.translations.push(translation32);

	var text81 = texts.Text.create(model);

	var clientTemplate32 = pages.ClientTemplate.create(model);
	clientTemplate32.template = text80;   // Note: for this property a default value is defined.
	clientTemplate32.fallback = text81;   // Note: for this property a default value is defined.

	var formattingInfo10 = pages.FormattingInfo.create(model);

	var noClientAction49 = pages.NoClientAction.create(model);

	var recipeCategoryNameInput1 = pages.TextBox.create(model);
	recipeCategoryNameInput1.name = "recipeCategoryNameInput";
	recipeCategoryNameInput1.appearance = appearance33;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.labelTemplate = clientTemplate31;
	recipeCategoryNameInput1.attributeRef = attributeRef11;
	recipeCategoryNameInput1.validation = widgetValidation11;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.onChangeAction = noClientAction46;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.onEnterAction = noClientAction47;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.onLeaveAction = noClientAction48;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.placeholderTemplate = clientTemplate32;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.formattingInfo = formattingInfo10;   // Note: for this property a default value is defined.
	recipeCategoryNameInput1.onEnterKeyPressAction = noClientAction49;   // Note: for this property a default value is defined.

	var appearance34 = pages.Appearance.create(model);

	var translation33 = texts.Translation.create(model);
	translation33.languageCode = "en_US";
	translation33.text = "Remove";

	var text82 = texts.Text.create(model);
	text82.translations.push(translation33);

	var text83 = texts.Text.create(model);

	var clientTemplate33 = pages.ClientTemplate.create(model);
	clientTemplate33.template = text82;   // Note: for this property a default value is defined.
	clientTemplate33.fallback = text83;   // Note: for this property a default value is defined.

	var text84 = texts.Text.create(model);

	var microflowSettings8 = pages.MicroflowSettings.create(model);
	microflowSettings8.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_RemoveCategory");

	var microflowClientAction5 = pages.MicroflowClientAction.create(model);
	microflowClientAction5.microflowSettings = microflowSettings8;   // Note: for this property a default value is defined.

	var recipeCategoryRemoveButton1 = pages.ActionButton.create(model);
	recipeCategoryRemoveButton1.name = "recipeCategoryRemoveButton";
	recipeCategoryRemoveButton1.appearance = appearance34;   // Note: for this property a default value is defined.
	recipeCategoryRemoveButton1.caption = clientTemplate33;   // Note: for this property a default value is defined.
	recipeCategoryRemoveButton1.tooltip = text84;   // Note: for this property a default value is defined.
	recipeCategoryRemoveButton1.renderType = pages.RenderType.Link;
	recipeCategoryRemoveButton1.action = microflowClientAction5;   // Note: for this property a default value is defined.

	var noClientAction50 = pages.NoClientAction.create(model);

	var noClientAction51 = pages.NoClientAction.create(model);

	var recipeCategoryList1 = pages.ListView.create(model);
	recipeCategoryList1.name = "recipeCategoryList";
	recipeCategoryList1.appearance = appearance32;   // Note: for this property a default value is defined.
	recipeCategoryList1.dataSource = microflowSource3;
	recipeCategoryList1.widgets.push(recipeCategoryNameInput1);
	recipeCategoryList1.widgets.push(recipeCategoryRemoveButton1);
	recipeCategoryList1.clickAction = noClientAction50;   // Note: for this property a default value is defined.
	recipeCategoryList1.editable = true;
	recipeCategoryList1.pullDownAction = noClientAction51;   // Note: for this property a default value is defined.

	var appearance35 = pages.Appearance.create(model);

	var translation34 = texts.Translation.create(model);
	translation34.languageCode = "en_US";
	translation34.text = "Add a category";

	var text85 = texts.Text.create(model);
	text85.translations.push(translation34);

	var text86 = texts.Text.create(model);

	var clientTemplate34 = pages.ClientTemplate.create(model);
	clientTemplate34.template = text85;   // Note: for this property a default value is defined.
	clientTemplate34.fallback = text86;   // Note: for this property a default value is defined.

	var text87 = texts.Text.create(model);

	var microflowSettings9 = pages.MicroflowSettings.create(model);
	microflowSettings9.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_AddCategory");

	var microflowClientAction6 = pages.MicroflowClientAction.create(model);
	microflowClientAction6.microflowSettings = microflowSettings9;   // Note: for this property a default value is defined.

	var recipeCategoryAddButton1 = pages.ActionButton.create(model);
	recipeCategoryAddButton1.name = "recipeCategoryAddButton";
	recipeCategoryAddButton1.appearance = appearance35;   // Note: for this property a default value is defined.
	recipeCategoryAddButton1.caption = clientTemplate34;   // Note: for this property a default value is defined.
	recipeCategoryAddButton1.tooltip = text87;   // Note: for this property a default value is defined.
	recipeCategoryAddButton1.renderType = pages.RenderType.Link;
	recipeCategoryAddButton1.action = microflowClientAction6;   // Note: for this property a default value is defined.

	var noClientAction52 = pages.NoClientAction.create(model);

	var recipeCategoryPanel1 = pages.DivContainer.create(model);
	recipeCategoryPanel1.name = "recipeCategoryPanel";
	recipeCategoryPanel1.appearance = appearance30;   // Note: for this property a default value is defined.
	recipeCategoryPanel1.widgets.push(recipeCategoryHeader1);
	recipeCategoryPanel1.widgets.push(recipeCategoryList1);
	recipeCategoryPanel1.widgets.push(recipeCategoryAddButton1);
	recipeCategoryPanel1.onClickAction = noClientAction52;   // Note: for this property a default value is defined.

	var appearance36 = pages.Appearance.create(model);

	var layoutGridColumn3 = pages.LayoutGridColumn.create(model);
	layoutGridColumn3.weight = 6;
	layoutGridColumn3.widgets.push(stepPanel1);
	layoutGridColumn3.widgets.push(ingredientPanel1);
	layoutGridColumn3.widgets.push(recipeCategoryPanel1);
	layoutGridColumn3.appearance = appearance36;   // Note: for this property a default value is defined.

	var appearance37 = pages.Appearance.create(model);

	var layoutGridRow2 = pages.LayoutGridRow.create(model);
	layoutGridRow2.columns.push(layoutGridColumn2);
	layoutGridRow2.columns.push(layoutGridColumn3);
	layoutGridRow2.appearance = appearance37;   // Note: for this property a default value is defined.

	var appearance38 = pages.Appearance.create(model);

	var translation35 = texts.Translation.create(model);
	translation35.languageCode = "en_US";
	translation35.text = "Save recipe";

	var text88 = texts.Text.create(model);
	text88.translations.push(translation35);

	var text89 = texts.Text.create(model);

	var clientTemplate35 = pages.ClientTemplate.create(model);
	clientTemplate35.template = text88;   // Note: for this property a default value is defined.
	clientTemplate35.fallback = text89;   // Note: for this property a default value is defined.

	var text90 = texts.Text.create(model);

	var pageVariable5 = pages.PageVariable.create(model);

	var microflowParameterMapping4 = pages.MicroflowParameterMapping.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	microflowParameterMapping4.__parameter.updateWithRawValue("MyFirstModule.ACT_SaveRecipe.HomeContext");
	microflowParameterMapping4.variable = pageVariable5;

	var microflowSettings10 = pages.MicroflowSettings.create(model);
	microflowSettings10.microflow = model.findMicroflowByQualifiedName("MyFirstModule.ACT_SaveRecipe");
	microflowSettings10.parameterMappings.push(microflowParameterMapping4);

	var microflowClientAction7 = pages.MicroflowClientAction.create(model);
	microflowClientAction7.microflowSettings = microflowSettings10;   // Note: for this property a default value is defined.

	var saveRecipeButton1 = pages.ActionButton.create(model);
	saveRecipeButton1.name = "saveRecipeButton";
	saveRecipeButton1.appearance = appearance38;   // Note: for this property a default value is defined.
	saveRecipeButton1.caption = clientTemplate35;   // Note: for this property a default value is defined.
	saveRecipeButton1.tooltip = text90;   // Note: for this property a default value is defined.
	saveRecipeButton1.action = microflowClientAction7;   // Note: for this property a default value is defined.

	var appearance39 = pages.Appearance.create(model);

	var translation36 = texts.Translation.create(model);
	translation36.languageCode = "en_US";
	translation36.text = "Cancel";

	var text91 = texts.Text.create(model);
	text91.translations.push(translation36);

	var text92 = texts.Text.create(model);

	var clientTemplate36 = pages.ClientTemplate.create(model);
	clientTemplate36.template = text91;   // Note: for this property a default value is defined.
	clientTemplate36.fallback = text92;   // Note: for this property a default value is defined.

	var text93 = texts.Text.create(model);

	var closePageClientAction1 = pages.ClosePageClientAction.create(model);

	var cancelRecipeButton1 = pages.ActionButton.create(model);
	cancelRecipeButton1.name = "cancelRecipeButton";
	cancelRecipeButton1.appearance = appearance39;   // Note: for this property a default value is defined.
	cancelRecipeButton1.caption = clientTemplate36;   // Note: for this property a default value is defined.
	cancelRecipeButton1.tooltip = text93;   // Note: for this property a default value is defined.
	cancelRecipeButton1.renderType = pages.RenderType.Link;
	cancelRecipeButton1.action = closePageClientAction1;   // Note: for this property a default value is defined.

	var appearance40 = pages.Appearance.create(model);

	var layoutGridColumn4 = pages.LayoutGridColumn.create(model);
	layoutGridColumn4.weight = -1;
	layoutGridColumn4.widgets.push(saveRecipeButton1);
	layoutGridColumn4.widgets.push(cancelRecipeButton1);
	layoutGridColumn4.appearance = appearance40;   // Note: for this property a default value is defined.

	var appearance41 = pages.Appearance.create(model);

	var layoutGridRow3 = pages.LayoutGridRow.create(model);
	layoutGridRow3.columns.push(layoutGridColumn4);
	layoutGridRow3.appearance = appearance41;   // Note: for this property a default value is defined.

	var newRecipeGrid1 = pages.LayoutGrid.create(model);
	newRecipeGrid1.name = "newRecipeGrid";
	newRecipeGrid1.appearance = appearance2;   // Note: for this property a default value is defined.
	newRecipeGrid1.rows.push(layoutGridRow1);
	newRecipeGrid1.rows.push(layoutGridRow2);
	newRecipeGrid1.rows.push(layoutGridRow3);

	var text94 = texts.Text.create(model);

	var newRecipeDataView1 = pages.DataView.create(model);
	newRecipeDataView1.name = "newRecipeDataView";
	newRecipeDataView1.appearance = appearance1;   // Note: for this property a default value is defined.
	newRecipeDataView1.dataSource = dataViewSource1;
	newRecipeDataView1.widgets.push(newRecipeGrid1);
	newRecipeDataView1.showFooter = false;
	newRecipeDataView1.noEntityMessage = text94;   // Note: for this property a default value is defined.

	var layoutCallArgument1 = pages.LayoutCallArgument.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	layoutCallArgument1.__parameter.updateWithRawValue("Atlas_Core.Atlas_TopBar.Main");
	layoutCallArgument1.widgets.push(newRecipeDataView1);

	var layoutCall1 = pages.LayoutCall.create(model);
	layoutCall1.layout = model.findLayoutByQualifiedName("Atlas_Core.Atlas_TopBar");
	layoutCall1.arguments.push(layoutCallArgument1);

	var translation37 = texts.Translation.create(model);
	translation37.languageCode = "en_US";
	translation37.text = "Add a recipe";

	var text95 = texts.Text.create(model);
	text95.translations.push(translation37);

	var appearance42 = pages.Appearance.create(model);

	var recipe_New1 = pages.Page.createIn(unit);
	recipe_New1.name = "Recipe_New";
	recipe_New1.canvasWidth = 1200;
	recipe_New1.parameters.push(newRecipe1);
	recipe_New1.parameters.push(homeContext1);
	recipe_New1.layoutCall = layoutCall1;   // Note: for this property a default value is defined.
	recipe_New1.title = text95;   // Note: for this property a default value is defined.
	recipe_New1.appearance = appearance42;   // Note: for this property a default value is defined.
	recipe_New1.allowedRoles.push(model.findModuleRoleByQualifiedName("MyFirstModule.User"));

	pageVariable1.pageParameter = newRecipe1;

	pageVariable2.widget = newRecipeDataView1;
	pageVariable2.pageParameter = newRecipe1;

	pageVariable3.widget = newRecipeDataView1;
	pageVariable3.pageParameter = newRecipe1;

	pageVariable4.widget = newRecipeDataView1;
	pageVariable4.pageParameter = newRecipe1;

	pageVariable5.pageParameter = homeContext1;

})